package com.ner.landslide.presentation.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf
import com.ner.landslide.domain.model.Alert
import com.ner.landslide.domain.model.AlertSeverity

/**
 * Reactive localized strings model for Bhoochetak.
 * Directly reacts to locale switches across English, Hindi, Assamese, Bengali, and Nepali.
 */
data class AppStrings(
    val langCode: String,

    // Header & Brand
    val telemetryRadarActive: String,
    val appTitle: String,
    val appSubtitle: String,

    // Telemetry Cards
    val rainfall: String,
    val soilSat: String,
    val sectors: String,
    val live: String,

    // Prominent SOS Hero
    val emergencySosTitle: String,
    val emergencySosSubtitle: String,
    val sosButtonLabel: String,
    val sosButtonSub: String,
    val transmit: String,
    val triggerSosPrompt: String,
    val sosDescription: String,
    val cancel: String,

    // AI Hazard Core
    val aiHazardNeuralCore: String,
    val online: String,
    val offline: String,
    val aiHazardDescription: String,
    val calculateRisk: String,
    val doppler: String,

    // Regional Hazard Feed & Severities
    val regionalHazardFeed: String,
    val activeAlertsSuffix: String,
    val liveFeedBadge: String,
    val filterAll: String,
    val filterCritical: String,
    val filterWarning: String,
    val filterAdvisory: String,
    val severityCritical: String,
    val severityHigh: String,
    val severityModerate: String,
    val severityLow: String,
    val directiveEvacuate: String,
    val directiveHigh: String,
    val directiveModerate: String,
    val directiveLow: String,

    // Default Localized Alert Data
    val alertNh10Title: String,
    val alertNh10Desc: String,
    val alertDzonguTitle: String,
    val alertDzonguDesc: String,
    val alertHaflongTitle: String,
    val alertHaflongDesc: String,

    // Rain Watch Screen (Formerly Doppler)
    val rainWatchTitle: String,
    val rainWatchSub: String,
    val lastUpdated: String,
    val radarCoverage: String,
    val hourlyForecast: String,
    val rainfallTotal: String,

    // Incident Report Screen
    val reportScreenTitle: String,
    val reportScreenSub: String,
    val step1Title: String,
    val step2Title: String,
    val autoDetectLocation: String,
    val detectingLocation: String,
    val locationFieldLabel: String,
    val locationFieldHint: String,
    val permDialogTitle: String,
    val permDialogDesc: String,
    val grantPermission: String,
    val gpsDisabledTitle: String,
    val gpsDisabledDesc: String,
    val openSettings: String,
    val hazardType: String,
    val severityLevel: String,
    val describeObservation: String,
    val transmitReport: String,

    // Prediction Screen
    val predictionScreenTitle: String,
    val predictionScreenSub: String,
    val geotechnicalScenarios: String,
    val scenarioSub: String,
    val scenarioCloudburst: String,
    val scenarioModerate: String,
    val scenarioDry: String,
    val slopeTelemetryHeader: String,
    val elevation: String,
    val slopeAngle: String,
    val rainfall1d: String,
    val rainfall3d: String,
    val rainfall7d: String,
    val soilMoisture: String,
    val lithology: String,
    val landCover: String,
    val runAssessment: String,
    val runningInference: String,
    val failureProbability: String,
    val contributingFactors: String,

    // Navigation Tabs
    val tabAlerts: String,
    val tabMap: String,
    val tabReport: String,
    val tabProfile: String,

    // Language Dialog
    val languageDialogTitle: String,
    val languageDialogSub: String,
    val filterByState: String,

    // Top Bar & Identity
    val safetyMonitorActive: String,
    val roleCitizen: String,
    val soilSatUnit: String,
    val defaultSectorName: String,

    // Hero AI Feature Card
    val checkLandslideRiskTitle: String,
    val checkLandslideRiskDesc: String,
    val checkMyRiskBtn: String,
    val rainRadarBtn: String,

    // Offline & SOS Feedback
    val offlineModeCached: String,
    val offlineNotice: String,
    val offlineSosDispatchedTitle: String,
    val offlineSosDispatchedDesc: String,
    val cloudSosDispatchedTitle: String,
    val cloudSosDispatchedDesc: String
)

fun AlertSeverity.toLocalizedLabel(strings: AppStrings): String = when (this) {
    AlertSeverity.CRITICAL -> strings.severityCritical
    AlertSeverity.HIGH -> strings.severityHigh
    AlertSeverity.MODERATE -> strings.severityModerate
    AlertSeverity.LOW -> strings.severityLow
}

fun AlertSeverity.toLocalizedDirective(strings: AppStrings): String = when (this) {
    AlertSeverity.CRITICAL -> strings.directiveEvacuate
    AlertSeverity.HIGH -> strings.directiveHigh
    AlertSeverity.MODERATE -> strings.directiveModerate
    AlertSeverity.LOW -> strings.directiveLow
}

fun Alert.getLocalizedTitle(strings: AppStrings): String = when (this.id) {
    "alert_nh10" -> strings.alertNh10Title
    "alert_dzongu" -> strings.alertDzonguTitle
    "alert_haflong" -> strings.alertHaflongTitle
    else -> this.title
}

fun Alert.getLocalizedDescription(strings: AppStrings): String = when (this.id) {
    "alert_nh10" -> strings.alertNh10Desc
    "alert_dzongu" -> strings.alertDzonguDesc
    "alert_haflong" -> strings.alertHaflongDesc
    else -> this.description
}

object AppStringsRepository {

    val EN = AppStrings(
        langCode = "en",
        telemetryRadarActive = "TELEMETRY RADAR: ACTIVE",
        appTitle = "BHOOCHETAK",
        appSubtitle = "Himalayan Landslide Early Warning & Response",
        rainfall = "RAINFALL",
        soilSat = "SOIL SAT",
        sectors = "SECTORS",
        live = "Live",
        emergencySosTitle = "EMERGENCY SOS DISPATCH",
        emergencySosSubtitle = "One-tap GNSS broadcast to SDRF / NDMA",
        sosButtonLabel = "SEND EMERGENCY SOS NOW",
        sosButtonSub = "Instant GNSS broadcast to SDRF • Works Offline via SMS",
        transmit = "TRANSMIT",
        triggerSosPrompt = "TRIGGER EMERGENCY SOS?",
        sosDescription = "This broadcasts your verified GPS coordinates directly to the State Disaster Management Authority (SDMA) and District Incident Response Teams.\n\nUse solely in case of immediate slope failure, structural collapse, or life hazard.",
        cancel = "CANCEL",
        aiHazardNeuralCore = "AI HAZARD NEURAL CORE",
        online = "ONLINE",
        offline = "OFFLINE",
        aiHazardDescription = "Evaluate geotechnical slope failure probability using live 24h rainfall saturation, antecedent precipitation index, and digital elevation models.",
        calculateRisk = "Calculate Risk",
        doppler = "Doppler",
        regionalHazardFeed = "REGIONAL HAZARD FEED",
        activeAlertsSuffix = "Active Warnings in Eastern Himalayas",
        liveFeedBadge = "LIVE FEED",
        filterAll = "All",
        filterCritical = "Critical",
        filterWarning = "High",
        filterAdvisory = "Moderate",
        severityCritical = "Critical Hazard",
        severityHigh = "High Risk",
        severityModerate = "Moderate Risk",
        severityLow = "Low Risk",
        directiveEvacuate = "🚨 Immediate evacuation recommended: avoid downhill slopes",
        directiveHigh = "⚠️ High alert: soil near saturation, restrict travel on hill passes",
        directiveModerate = "⚡ Watch status: monitor drainage culverts and road cuts",
        directiveLow = "✅ Normal: stable ground conditions within acceptable safety margins",
        alertNh10Title = "Severe Slope Instability Warning — NH-10",
        alertNh10Desc = "Heavy rainfall detected in Sevoke-Kalimpong corridor. Active debris slips between 29th Mile and Teesta Bazar. Night vehicular transit restricted.",
        alertDzonguTitle = "Critical Landslide Evacuation Watch — Dzongu Valley",
        alertDzonguDesc = "Pore water pressure sensors exceeding safety threshold (18.5 kPa). Soil saturation at 86%. Downhill evacuation protocol in effect.",
        alertHaflongTitle = "Moderate Risk Advisory — Haflong Corridor",
        alertHaflongDesc = "Antecedent 3-day rainfall at 124 mm. Hill cutting zones along Lumding-Badarpur railway section under active sensor surveillance.",
        rainWatchTitle = "Rain Watch",
        rainWatchSub = "Live Rain & Cloud Radar",
        lastUpdated = "Last updated",
        radarCoverage = "Radar Station Coverage",
        hourlyForecast = "24-Hour Precipitation Forecast",
        rainfallTotal = "Total Estimated Rain",
        reportScreenTitle = "Incident Report",
        reportScreenSub = "Field Observation & GPS Dispatch",
        step1Title = "Location & Evidence",
        step2Title = "Classification",
        autoDetectLocation = "Auto-Detect My Location",
        detectingLocation = "Detecting GPS location...",
        locationFieldLabel = "Sector / District Location",
        locationFieldHint = "e.g. Namchi, South Sikkim",
        permDialogTitle = "Location Access Required",
        permDialogDesc = "Bhoochetak requires GPS access to detect your exact mountain sector and route rescue teams to your coordinates.",
        grantPermission = "Grant Permission",
        gpsDisabledTitle = "Turn on GPS Location",
        gpsDisabledDesc = "Your phone's location services are currently turned off. Please enable location to automatically fill your district and coordinates.",
        openSettings = "Open Location Settings",
        hazardType = "Hazard Type",
        severityLevel = "Severity Level",
        describeObservation = "Describe ground movement, cracks, or blocked roads",
        transmitReport = "TRANSMIT DISASTER REPORT",
        predictionScreenTitle = "AI Risk Prediction",
        predictionScreenSub = "Bhoochetak XGBoost Model",
        geotechnicalScenarios = "Geotechnical Scenarios",
        scenarioSub = "Pick a quick simulation preset or enter data below",
        scenarioCloudburst = "Monsoon Cloudburst",
        scenarioModerate = "Moderate Hill Shower",
        scenarioDry = "Dry Hill Slope",
        slopeTelemetryHeader = "Slope & Meteorological Telemetry",
        elevation = "Elevation (MSL in meters)",
        slopeAngle = "Slope Inclination (degrees °)",
        rainfall1d = "24-Hour Rainfall (mm)",
        rainfall3d = "3-Day Antecedent Rain (mm)",
        rainfall7d = "7-Day Cumulative Rain (mm)",
        soilMoisture = "Volumetric Soil Moisture (% sat)",
        lithology = "Lithology Group (Bedrock Type)",
        landCover = "Land Cover Classification",
        runAssessment = "RUN GEOTECHNICAL ASSESSMENT",
        runningInference = "Evaluating Geotechnical Physics...",
        failureProbability = "Estimated Failure Probability",
        contributingFactors = "Primary Contributing Factors",
        tabAlerts = "Alerts",
        tabMap = "Map",
        tabReport = "Report",
        tabProfile = "Profile",
        languageDialogTitle = "Language & Dialect",
        languageDialogSub = "Eastern Himalayan Region",
        filterByState = "Filter by State / Region",
        safetyMonitorActive = "SAFETY MONITOR: ACTIVE",
        roleCitizen = "Citizen",
        soilSatUnit = "Sat",
        defaultSectorName = "SECTOR: Eastern Himalayas (Sikkim / Assam Corridor)",
        checkLandslideRiskTitle = "CHECK LANDSLIDE RISK",
        checkLandslideRiskDesc = "Check if your village, slope, or travel route is at risk of landslide based on recent rain and steep terrain.",
        checkMyRiskBtn = "Check My Risk",
        rainRadarBtn = "Rain Radar",
        offlineModeCached = "OFFLINE MODE — CACHED RISK DATA",
        offlineNotice = "Offline — showing last known risk data. Emergency SOS and disaster reports are queued locally for transmission.",
        offlineSosDispatchedTitle = "OFFLINE SOS DISPATCHED VIA SMS",
        offlineSosDispatchedDesc = "Distress beacon sent via Cellular SMS to 112 with GPS coordinates & Maps pin. Auto-queued to sync with SDRF Cloud Dashboard when internet returns.",
        cloudSosDispatchedTitle = "EMERGENCY SOS DISPATCHED (CLOUD)",
        cloudSosDispatchedDesc = "Your GPS telemetry has been relayed to SDRF / NDMA quick-response teams."
    )

    val HI = AppStrings(
        langCode = "hi",
        telemetryRadarActive = "टेलीमेट्री रडार: सक्रिय",
        appTitle = "भूचेतक",
        appSubtitle = "हिमालयी भूस्खलन पूर्व चेतावनी एवं त्वरित राहत",
        rainfall = "वर्षा",
        soilSat = "मिट्टी नमी",
        sectors = "सेक्टर",
        live = "लाइव",
        emergencySosTitle = "आपातकालीन संकट संदेश (SOS)",
        emergencySosSubtitle = "SDRF / NDMA को एक-टैप जीपीएस प्रसारण",
        sosButtonLabel = "आपातकालीन SOS तुरंत भेजें",
        sosButtonSub = "बचाव दल को तुरंत जीपीएस संदेश • ऑफलाइन SMS द्वारा कार्यरत",
        transmit = "भेजें",
        triggerSosPrompt = "आपातकालीन SOS भेजें?",
        sosDescription = "यह आपके सटीक GPS निर्देशांक सीधे राज्य आपदा प्रबंधन प्राधिकरण और राहत बचाव दलों को भेजता है। केवल आपात स्थिति में उपयोग करें।",
        cancel = "रद्द करें",
        aiHazardNeuralCore = "एआई भूस्खलन जांच कोर",
        online = "ऑनलाइन",
        offline = "ऑफलाइन",
        aiHazardDescription = "24 घंटे की बारिश और ढलान के आधार पर भूस्खलन के खतरे का आकलन करें।",
        calculateRisk = "जोखिम जांचें",
        doppler = "रडार",
        regionalHazardFeed = "क्षेत्रीय आपदा चेतावनी सूचना",
        activeAlertsSuffix = "पूर्वी हिमालय में सक्रिय चेतावनियां",
        liveFeedBadge = "लाइव सूचना",
        filterAll = "सभी",
        filterCritical = "अति गंभीर",
        filterWarning = "उच्च",
        filterAdvisory = "मध्यम",
        severityCritical = "अति गंभीर संकट",
        severityHigh = "उच्च जोखिम",
        severityModerate = "मध्यम जोखिम",
        severityLow = "कम जोखिम",
        directiveEvacuate = "🚨 तुरंत सुरक्षित स्थान पर जाएं: निचली ढलानों से दूर रहें",
        directiveHigh = "⚠️ उच्च सतर्कता: मिट्टी पूरी तरह गीली है, पहाड़ी रास्तों पर यात्रा से बचें",
        directiveModerate = "⚡ नजर रखें: पहाड़ी कटाव और नालों पर ध्यान दें",
        directiveLow = "✅ सामान्य: जमीन स्थिर और सुरक्षित है",
        alertNh10Title = "तीव्र ढलान अस्थिरता चेतावनी — NH-10",
        alertNh10Desc = "सेवोक-कालिम्पोंग मार्ग में भारी बारिश दर्ज। 29वें मील और तीस्ता बाजार के बीच मलबा खिसका। रात का आवागमन प्रतिबंधित।",
        alertDzonguTitle = "गंभीर भूस्खलन निकासी चेतावनी — जोंगु घाटी",
        alertDzonguDesc = "मिट्टी में पानी का दबाव सीमा से अधिक (18.5 kPa)। मिट्टी संतृप्ति 86%। ढलान से सुरक्षित निकासी के निर्देश।",
        alertHaflongTitle = "मध्यम जोखिम सलाह — हाफलोंग कॉरिडोर",
        alertHaflongDesc = "पिछले 3 दिनों में 124 मिमी बारिश। लुमडिंग-बदरपुर रेलवे लाइन के पास पहाड़ी कटाव क्षेत्रों पर सतत निगरानी जारी।",
        rainWatchTitle = "बारिश निगरानी (Rain Watch)",
        rainWatchSub = "लाइव बारिश और बादल रडार",
        lastUpdated = "अंतिम अपडेट",
        radarCoverage = "रडार स्टेशन कवरेज",
        hourlyForecast = "24 घंटे का वर्षा पूर्वानुमान",
        rainfallTotal = "कुल अनुमानित वर्षा",
        reportScreenTitle = "आपदा घटना रिपोर्ट",
        reportScreenSub = "मैदानी अवलोकन एवं जीपीएस प्रेषण",
        step1Title = "स्थान और साक्ष्य",
        step2Title = "वर्गीकरण",
        autoDetectLocation = "मेरा स्थान स्वतः पता करें",
        detectingLocation = "जीपीएस स्थान खोजा जा रहा है...",
        locationFieldLabel = "क्षेत्र / जिला स्थान",
        locationFieldHint = "उदा. नामची, दक्षिण सिक्किम",
        permDialogTitle = "स्थान (GPS) अनुमति आवश्यक है",
        permDialogDesc = "भूचेतक को आपके पहाड़ी क्षेत्र का पता लगाने और बचाव दल को आपके पास भेजने के लिए जीपीएस अनुमति की आवश्यकता है।",
        grantPermission = "अनुमति दें",
        gpsDisabledTitle = "जीपीएस (GPS) चालू करें",
        gpsDisabledDesc = "आपके फोन का लोकेशन सिस्टम बंद है। कृपया जिले और निर्देशांक स्वतः भरने के लिए जीपीएस चालू करें।",
        openSettings = "लोकेशन सेटिंग्स खोलें",
        hazardType = "आपदा का प्रकार",
        severityLevel = "गंभीरता स्तर",
        describeObservation = "जमीन में दरार, भूस्खलन या सड़क बंद होने का विवरण दें",
        transmitReport = "आपदा रिपोर्ट भेजें",
        predictionScreenTitle = "एआई जोखिम भविष्यवाणी",
        predictionScreenSub = "भूचेतक XGBoost मॉडल",
        geotechnicalScenarios = "भू-प्राविधिक परिदृश्य",
        scenarioSub = "त्वरित सिमुलेशन चुनें या नीचे डेटा भरें",
        scenarioCloudburst = "बादल फटना (भारी वर्षा)",
        scenarioModerate = "मध्यम पहाड़ी वर्षा",
        scenarioDry = "सूखी पहाड़ी ढलान",
        slopeTelemetryHeader = "ढलान और मौसम विज्ञान टेलीमेट्री",
        elevation = "समुद्र तल से ऊंचाई (मीटर MSL)",
        slopeAngle = "ढलान कोण (डिग्री °)",
        rainfall1d = "24 घंटे की बारिश (मिमी)",
        rainfall3d = "3 दिन की संचित बारिश (मिमी)",
        rainfall7d = "7 दिन की कुल बारिश (मिमी)",
        soilMoisture = "मिट्टी नमी संतृप्ति (% sat)",
        lithology = "भूवैज्ञानिक चट्टान वर्ग (Lithology)",
        landCover = "भूमि आवरण वर्ग (Land Cover)",
        runAssessment = "जोखिम की गणना करें",
        runningInference = "गणना चल रही है...",
        failureProbability = "संभावित भूस्खलन संभावना",
        contributingFactors = "प्रमुख सहायक कारक",
        tabAlerts = "सूचनाएं",
        tabMap = "नक्शा",
        tabReport = "रिपोर्ट",
        tabProfile = "प्रोफाइल",
        languageDialogTitle = "भाषा और बोली",
        languageDialogSub = "पूर्वी हिमालय क्षेत्र",
        filterByState = "राज्य / क्षेत्र अनुसार खोजें",
        safetyMonitorActive = "सुरक्षा निगरानी: सक्रिय",
        roleCitizen = "नागरिक",
        soilSatUnit = "संतृप्ति",
        defaultSectorName = "सेक्टर: पूर्वी हिमालय (सिक्किम / असम कॉरिडोर)",
        checkLandslideRiskTitle = "भूस्खलन जोखिम जांचें",
        checkLandslideRiskDesc = "हालिया बारिश और खड़ी ढलान के आधार पर अपने गांव, मार्ग या पहाड़ी ढलान के भूस्खलन जोखिम की जांच करें।",
        checkMyRiskBtn = "जोखिम जांचें",
        rainRadarBtn = "वर्षा रडार",
        offlineModeCached = "ऑफलाइन मोड — सुरक्षित डेटा",
        offlineNotice = "ऑफलाइन — पुराना जोखिम डेटा प्रदर्शित हो रहा है। आपातकालीन SOS और रिपोर्ट ऑफलाइन संदेश द्वारा भेजी जाएंगी।",
        offlineSosDispatchedTitle = "एसएमएस द्वारा ऑफलाइन SOS भेजा गया",
        offlineSosDispatchedDesc = "जीपीएस निर्देशांक सहित 112 पर एसएमएस आपातकालीन संदेश भेजा गया। इंटरनेट आने पर स्वचालित सिंक होगा।",
        cloudSosDispatchedTitle = "आपातकालीन SOS भेजा गया (क्लाउड)",
        cloudSosDispatchedDesc = "आपके जीपीएस निर्देशांक SDRF / NDMA त्वरित राहत दल को प्रेषित कर दिए गए हैं।"
    )

    val AS = AppStrings(
        langCode = "as",
        telemetryRadarActive = "টেলিমেট্ৰি ৰাডাৰ: সক্ৰিয়",
        appTitle = "ভূচেতক",
        appSubtitle = "হিমালয়ৰ ভূমিস্খলন পূৰ্ব সতৰ্কবাণী আৰু উদ্ধাৰ",
        rainfall = "বৰষুণ",
        soilSat = "মাটিৰ আৰ্দ্ৰতা",
        sectors = "ছেক্টৰ",
        live = "লাইভ",
        emergencySosTitle = "জৰুৰীকালীন SOS প্ৰেৰণ",
        emergencySosSubtitle = "SDRF / NDMA লৈ ১-টেপ GNSS বাৰ্তা",
        sosButtonLabel = "জৰুৰীকালীন SOS এতিয়াই পঠিয়াওক",
        sosButtonSub = "উদ্ধাৰকাৰী দললৈ তাৎক্ষণিক বাৰ্তা • অফলাইন SMS ৰেও কাৰ্যক্ষম",
        transmit = "প্ৰেৰণ কৰক",
        triggerSosPrompt = "জৰুৰীকালীন SOS পঠিয়াবনে?",
        sosDescription = "ই আপোনাৰ সঠিক GPS স্থানাংক পোনপটীয়াকৈ ৰাজ্যিক দুৰ্যোগ ব্যৱস্থাপনা আৰু উদ্ধাৰকাৰী দললৈ প্ৰেৰণ কৰিব। কেৱল বিপদৰ সময়ত ব্যৱহাৰ কৰক।",
        cancel = "বাতিল কৰক",
        aiHazardNeuralCore = "এআই ভূমিস্খলন পৰীক্ষা",
        online = "অনলাইন",
        offline = "অফলাইন",
        aiHazardDescription = "২৪ ঘণ্টাৰ বৰষুণ আৰু পাহাৰৰ ঢাল ব্যৱহাৰ কৰি ভূমিস্খলনৰ সম্ভাৱনা গণনা কৰক।",
        calculateRisk = "বিপদ পৰীক্ষা কৰক",
        doppler = "ৰাডাৰ",
        regionalHazardFeed = "আঞ্চলিক দুৰ্যোগ সতৰ্কবাণী",
        activeAlertsSuffix = "পূব হিমালয়ত সক্ৰিয় সতৰ্কবাণী",
        liveFeedBadge = "লাইভ ফিড",
        filterAll = "সকলো",
        filterCritical = "চৰম বিপদ",
        filterWarning = "উচ্চ",
        filterAdvisory = "মজলীয়া",
        severityCritical = "চৰম সংকট",
        severityHigh = "উচ্চ বিপদ",
        severityModerate = "মজলীয়া বিপদ",
        severityLow = "কম বিপদ",
        directiveEvacuate = "🚨 তাৎক্ষণিক সুৰক্ষিত স্থানলৈ যাওক: নিম্ন ঢাল পৰিহাৰ কৰক",
        directiveHigh = "⚠️ উচ্চ সতৰ্কতা: মাটি সম্পূর্ণ তিতিছে, পাহাৰীয়া পথত ভ্ৰমণ নকৰিব",
        directiveModerate = "⚡ সতৰ্ক দৃষ্টি ৰাখক: পাহাৰৰ কাটি লোৱা অংশ আৰু নলা নিৰীক্ষণ কৰক",
        directiveLow = "✅ স্বাভাৱিক: মাটি সুস্থিৰ আৰু সুৰক্ষিত",
        alertNh10Title = "তীব্র ঢাল অস্থিৰতা সতৰ্কবাণী — NH-10",
        alertNh10Desc = "ছেভক-কালিম্পং পথত প্ৰচণ্ড বৰষুণ। ২৯ মাইল আৰু তিস্তা বজাৰৰ মাজত শিল-মাটি খহিছে। ৰাতি যাতায়ত নিষিদ্ধ।",
        alertDzonguTitle = "ভূমিস্খলন আৰু স্থান খালী কৰাৰ সতৰ্কবাণী — জংগু উপত্যকা",
        alertDzonguDesc = "মাটিৰ পানীৰ চাপ বিপদসীমাৰ ওপৰত (18.5 kPa)। মাটিৰ আৰ্দ্ৰতা ৮৬%। সুৰক্ষিত স্থানলৈ যোৱাৰ নিৰ্দেশ।",
        alertHaflongTitle = "মজলীয়া বিপদ পৰামৰ্শ — হাফলং কৰিডৰ",
        alertHaflongDesc = "যোৱা ৩ দিনত ১২৪ মিমি বৰষুণ। লামডিং-বদৰপুৰ ৰে'ল পথৰ কাষৰ পাহাৰীয়া স্থানসমূহ নিৰীক্ষণত ৰখা হৈছে।",
        rainWatchTitle = "বৰষুণ নিৰীক্ষণ (Rain Watch)",
        rainWatchSub = "লাইভ বৰষুণ আৰু ডাৱৰ ৰাডাৰ",
        lastUpdated = "শেহতীয়া আপডেট",
        radarCoverage = "ৰাডাৰ ষ্টেচন এলেকা",
        hourlyForecast = "২৪ ঘণ্টাৰ বৰষুণৰ পূৰ্বানুমান",
        rainfallTotal = "মুঠ সম্ভাৱ্য বৰষুণ",
        reportScreenTitle = "ঘটনাৰ প্ৰতিবেদন",
        reportScreenSub = "ক্ষেত্ৰ নিৰীক্ষণ আৰু GPS প্ৰেৰণ",
        step1Title = "স্থান আৰু তথ্য-প্ৰমাণ",
        step2Title = "শ্ৰেণীবিভাজন",
        autoDetectLocation = "মোৰ স্থান নিজে বিচাৰক",
        detectingLocation = "GPS স্থান বিচৰা হৈছে...",
        locationFieldLabel = "এলেকা / জিলাৰ স্থান",
        locationFieldHint = "উদাহৰণ: নামচি, দক্ষিণ ছিকিম",
        permDialogTitle = "স্থান (GPS) অনুমতিৰ প্ৰয়োজন",
        permDialogDesc = "আপোনাৰ পাহাৰীয়া এলেকা নিৰ্ণয় কৰিবলৈ আৰু উদ্ধাৰকাৰী দল পঠিয়াবলৈ ভূচেতকক GPS অনুমতিৰ প্ৰয়োজন।",
        grantPermission = "অনুমতি দিয়ক",
        gpsDisabledTitle = "GPS স্থান অন কৰক",
        gpsDisabledDesc = "আপোনাৰ ফোনৰ লোকেশ্বন ছিষ্টেম বন্ধ আছে। জিলা আৰু স্থানাংক নিজে পূৰণ কৰিবলৈ অনুগ্ৰহ কৰি GPS অন কৰক।",
        openSettings = "ছেটিংছ খোলক",
        hazardType = "বিপদৰ প্ৰকাৰ",
        severityLevel = "বিপদৰ মাত্ৰা",
        describeObservation = "মাটি খহা, ফাট মেলা বা পথ বন্ধ হোৱাৰ বিৱৰণ দিয়ক",
        transmitReport = "বিপদৰ প্ৰতিবেদন প্ৰেৰণ কৰক",
        predictionScreenTitle = "এআই বিপদ পূৰ্বানুমান",
        predictionScreenSub = "ভূচেতক XGBoost মডেল",
        geotechnicalScenarios = "ভূ-কাৰিকৰী পৰিস্থিতি",
        scenarioSub = "দ্ৰুত পৰীক্ষা বাছনি কৰক বা তলত তথ্য দিয়ক",
        scenarioCloudburst = "মেঘভঙা প্ৰচণ্ড বৰষুণ",
        scenarioModerate = "মজলীয়া পাহাৰীয়া বৰষুণ",
        scenarioDry = "শুকান পাহাৰীয়া ঢাল",
        slopeTelemetryHeader = "ঢাল আৰু বতৰ বিজ্ঞান টেলিমেট্ৰি",
        elevation = "উচ্চতা (সমুদ্ৰপৃষ্ঠৰ পৰা m MSL)",
        slopeAngle = "ঢালৰ কোণ (ডিগ্ৰী °)",
        rainfall1d = "২৪ ঘণ্টাৰ বৰষুণ (mm)",
        rainfall3d = "৩ দিনৰ সঞ্চিত বৰষুণ (mm)",
        rainfall7d = "৭ দিনৰ মুঠ বৰষুণ (mm)",
        soilMoisture = "মাটিৰ আৰ্দ্ৰতা সম্পৃক্তি (% sat)",
        lithology = "ভূতাত্ত্বিক শিলা গোট (Lithology)",
        landCover = "ভূমি আৱৰণ শ্ৰেণী (Land Cover)",
        runAssessment = "বিপদৰ মূল্যাংকন কৰক",
        runningInference = "গণনা চলি আছে...",
        failureProbability = "ঢাল খহি পৰাৰ সম্ভাৱনা",
        contributingFactors = "প্ৰধান কাৰকসমূহ",
        tabAlerts = "সতৰ্কবাণী",
        tabMap = "মানচিত্ৰ",
        tabReport = "প্ৰতিবেদন",
        tabProfile = "প্ৰফাইল",
        languageDialogTitle = "ভাষা আৰু উপভাষা",
        languageDialogSub = "পূব হিমালয় অঞ্চল",
        filterByState = "ৰাজ্য / অঞ্চল অনুসৰি বাছক",
        safetyMonitorActive = "সুৰক্ষা নিৰীক্ষণ: সক্ৰিয়",
        roleCitizen = "নাগৰিক",
        soilSatUnit = "আৰ্দ্ৰতা",
        defaultSectorName = "ছেক্টৰ: পূব হিমালয় (চিকিম / অসম কৰিডৰ)",
        checkLandslideRiskTitle = "ভূমিস্খলন বিপদ পৰীক্ষা",
        checkLandslideRiskDesc = "শেহতীয়া বৰষুণ আৰু পাহাৰীয়া ঢালৰ ওপৰত ভিত্তি কৰি আপোনাৰ গাঁও বা যাতায়ত পথৰ বিপদ পৰীক্ষা কৰক।",
        checkMyRiskBtn = "বিপদ পৰীক্ষা কৰক",
        rainRadarBtn = "বৰষুণ ৰাডাৰ",
        offlineModeCached = "অফলাইন ম'ড — সংৰক্ষিত তথ্য",
        offlineNotice = "অফলাইন — পূৰ্বৰ বিপদৰ তথ্য দেখুওৱা হৈছে। জৰুৰীকালীন SOS আৰু প্ৰতিবেদন অফলাইন বাৰ্তাযোগে প্ৰেৰণ হ'ব।",
        offlineSosDispatchedTitle = "SMS যোগে অফলাইন SOS প্ৰেৰণ কৰা হ'ল",
        offlineSosDispatchedDesc = "GPS স্থানাংক সহ ১১২ নম্বৰলৈ জৰুৰীকালীন বাৰ্তা প্ৰেৰণ কৰা হ'ল। ইণ্টাৰনেট আহিলে ক্লাউডৰ সৈতে স্বয়ংক্ৰিয়ভাৱে সংযোগ হ'ব।",
        cloudSosDispatchedTitle = "জৰুৰীকালীন SOS প্ৰেৰণ কৰা হ'ল (ক্লাউড)",
        cloudSosDispatchedDesc = "আপোনাৰ GPS স্থানাংক SDRF / NDMA উদ্ধাৰকাৰী দললৈ প্ৰেৰণ কৰা হৈছে।"
    )

    val BN = AppStrings(
        langCode = "bn",
        telemetryRadarActive = "টেলিমেট্রি রাডার: সক্রিয়",
        appTitle = "ভূচেতক",
        appSubtitle = "হিমালয় ভূমিধস পূর্ব সতর্কতা ও উদ্ধার ব্যবস্থা",
        rainfall = "বৃষ্টিপাত",
        soilSat = "মাটির আর্দ্রতা",
        sectors = "সেক্টর",
        live = "লাইভ",
        emergencySosTitle = "জরুরি বিপদ সংকেত (SOS)",
        emergencySosSubtitle = "SDRF / NDMA-তে এক-ট্যাপ জিপিএস সম্প্রচার",
        sosButtonLabel = "জরুরি SOS এখনই পাঠান",
        sosButtonSub = "উদ্ধারকারী দলকে তাৎক্ষণিক জিপিএস বার্তা • অফলাইনেও SMS দ্বারা সক্রিয়",
        transmit = "প্রেরণ করুন",
        triggerSosPrompt = "জরুরি SOS পাঠাবেন?",
        sosDescription = "এটি আপনার সুনির্দিষ্ট GPS স্থানাঙ্ক সরাসরি রাজ্য দুর্যোগ ব্যবস্থাপনা ও উদ্ধারকারী দলের কাছে পাঠাবে। কেবল বিপদে ব্যবহার করুন।",
        cancel = "বাতিল",
        aiHazardNeuralCore = "এআই ভূমিধস পর্যবেক্ষণ",
        online = "অনলাইন",
        offline = "অফলাইন",
        aiHazardDescription = "২৪ ঘণ্টার বৃষ্টিপাত ও ঢালু জমির ভিত্তিতে ভূমিধসের ঝুঁকি নির্ণয় করুন।",
        calculateRisk = "ঝুঁকি নির্ণয়",
        doppler = "রাডার",
        regionalHazardFeed = "আঞ্চলিক দুর্যোগ সতর্কতা",
        activeAlertsSuffix = "পূর্ব হিমালয়ে সক্রিয় সতর্কবার্তা",
        liveFeedBadge = "লাইভ ফিড",
        filterAll = "সকল",
        filterCritical = "মারাত্মক",
        filterWarning = "উচ্চ",
        filterAdvisory = "মাঝারি",
        severityCritical = "মারাত্মক সংকট",
        severityHigh = "উচ্চ ঝুঁকি",
        severityModerate = "মাঝারি ঝুঁকি",
        severityLow = "কম ঝুঁকি",
        directiveEvacuate = "🚨 অবিলম্বে নিরাপদ স্থানে যান: ঢালু পথ এড়িয়ে চলুন",
        directiveHigh = "⚠️ উচ্চ সতর্কতা: মাটি অতিরিক্ত স্যাঁতসেঁতে, পাহাড়ি পথে ভ্রমণ এড়িয়ে চলুন",
        directiveModerate = "⚡ নজর রাখুন: পাহাড়ি ফাটল ও ড্রেনেজ পর্যবেক্ষণ করুন",
        directiveLow = "✅ স্বাভাবিক: ভূমি স্থিতিশীল ও নিরাপদ",
        alertNh10Title = "তীব্র ঢাল অস্থিরতার সতর্কতা — NH-10",
        alertNh10Desc = "সেভক-কালিম্পং করিডোরে ভারী বৃষ্টিপাত। ২৯ মাইল ও তিস্তা বাজারের মাঝে পাথর ও মাটি ধস। রাতের যান চলাচল নিষিদ্ধ।",
        alertDzonguTitle = "ভূমিধস ও জরুরি স্থানান্তর সতর্কতা — জংগু উপত্যকা",
        alertDzonguDesc = "মাটির পানির চাপ সহনসীমার বেশি (18.5 kPa)। মাটির আর্দ্রতা ৮৬%। তাৎক্ষণিক নিরাপদে সরে যাওয়ার নির্দেশ।",
        alertHaflongTitle = "মাঝারি ঝুঁকি পরামর্শ — হাফলং করিডোর",
        alertHaflongDesc = "বিগত ৩ দিনে ১২৪ মিমি বৃষ্টিপাত। লামডিং-বদরপুর রেললাইনের নিকটবর্তী পাহাড়ি ধসপ্রবণ এলাকায় নজরদারি চলছে।",
        rainWatchTitle = "বৃষ্টিপাত নজরদারি (Rain Watch)",
        rainWatchSub = "লাইভ বৃষ্টি ও মেঘ রাডার",
        lastUpdated = "সর্বশেষ আপডেট",
        radarCoverage = "রাডার স্টেশন কাভারেজ",
        hourlyForecast = "২৪ ঘণ্টার বৃষ্টিপাতের পূর্বাভাস",
        rainfallTotal = "মোট আনুমানিক বৃষ্টিপাত",
        reportScreenTitle = "দুর্যোগ ঘটনা রিপোর্ট",
        reportScreenSub = "মাঠের পর্যবেক্ষণ ও জিপিএস প্রেরণ",
        step1Title = "স্থান ও তথ্যপ্রমাণ",
        step2Title = "শ্রেণীবিভাগ",
        autoDetectLocation = "আমার অবস্থান স্বয়ংক্রিয়ভাবে খুঁজুন",
        detectingLocation = "জিপিএস অবস্থান খোঁজা হচ্ছে...",
        locationFieldLabel = "এলাকা / জেলার নাম",
        locationFieldHint = "যেমন: নামচি, দক্ষিণ সিকিম",
        permDialogTitle = "অবস্থান (GPS) অনুমতি প্রয়োজন",
        permDialogDesc = "আপনার সঠিক পাহাড়ি অঞ্চল শনাক্ত করতে এবং উদ্ধারকারী দল পাঠাতে ভূচেতকের GPS অনুমতি প্রয়োজন।",
        grantPermission = "অনুমতি দিন",
        gpsDisabledTitle = "GPS অবস্থান চালু করুন",
        gpsDisabledDesc = "আপনার ফোনের লোকেশন সার্ভিস বর্তমানে বন্ধ রয়েছে। জেলা ও স্থানাঙ্ক স্বয়ংক্রিয়ভাবে পূরণ করতে GPS চালু করুন।",
        openSettings = "সেটিংস খুলুন",
        hazardType = "বিপদের ধরন",
        severityLevel = "তীব্রতার মাত্রা",
        describeObservation = "মাটি ধস, ফাটল বা রাস্তা অবরুদ্ধ হওয়ার বিবরণ দিন",
        transmitReport = "দুর্যোগ রিপোর্ট প্রেরণ করুন",
        predictionScreenTitle = "এআই ঝুঁকি পূর্বাভাস",
        predictionScreenSub = "ভূচেতক XGBoost মডেল",
        geotechnicalScenarios = "ভূ-প্রকৌশল পরিস্থিতি",
        scenarioSub = "দ্রুত সিমুলেশন প্রিসেট বাছুন অথবা নিচে ডেটা লিখুন",
        scenarioCloudburst = "মৌসুমি মেঘভাঙা বৃষ্টি",
        scenarioModerate = "মাঝারি পাহাড়ী বৃষ্টি",
        scenarioDry = "শুকনো পাহাড়ী ঢাল",
        slopeTelemetryHeader = "ঢাল ও আবহাওয়া টেলিমেট্রি",
        elevation = "উচ্চতা (সমুদ্রপৃষ্ঠ থেকে m MSL)",
        slopeAngle = "ঢাল কোণ (ডিগ্রী °)",
        rainfall1d = "২৪ ঘণ্টার বৃষ্টিপাত (mm)",
        rainfall3d = "৩ দিনের পূর্ববর্তী বৃষ্টি (mm)",
        rainfall7d = "৭ দিনের মোট বৃষ্টি (mm)",
        soilMoisture = "মাটির আর্দ্রতা সম্পৃক্তি (% sat)",
        lithology = "ভূতাত্ত্বিক শিলা গ্রুপ (Lithology)",
        landCover = "ভূমি আচ্ছাদন (Land Cover)",
        runAssessment = "ভূ-কারিগরি ঝুঁকি মূল্যায়ন চালান",
        runningInference = "পূর্বাভাস চলছে...",
        failureProbability = "ঢাল ধসের আনুমানিক সম্ভাবনা",
        contributingFactors = "গুরুত্বপূর্ণ কারণসমূহ",
        tabAlerts = "সতর্কতা",
        tabMap = "মানচিত্র",
        tabReport = "প্রতিবেদন",
        tabProfile = "প্রোফাইল",
        languageDialogTitle = "ভাষা ও উপভাষা",
        languageDialogSub = "পূর্ব হিমালয় টেলিমেট্রি",
        filterByState = "রাজ্য / অঞ্চল অনুসারে ফিল্টার করুন",
        safetyMonitorActive = "সুরক্ষা পর্যবেক্ষণ: সক্রিয়",
        roleCitizen = "নাগরিক",
        soilSatUnit = "আর্দ্রতা",
        defaultSectorName = "সেক্টর: পূর্ব হিমালয় (সিকিম / আসাম করিডোর)",
        checkLandslideRiskTitle = "ভূমিধসের ঝুঁকি পরীক্ষা",
        checkLandslideRiskDesc = "সাম্প্রতিক বৃষ্টিপাত ও খাড়া ঢালের ওপর ভিত্তি করে আপনার এলাকা বা যাতায়াত পথের ঝুঁকি যাচাই করুন।",
        checkMyRiskBtn = "ঝুঁকি পরীক্ষা",
        rainRadarBtn = "বৃষ্টি রাডার",
        offlineModeCached = "অফলাইন মোড — সংরক্ষিত তথ্য",
        offlineNotice = "অফলাইন — সর্বশেষ প্রাপ্ত তথ্য প্রদর্শিত হচ্ছে। জরুরি SOS এবং রিপোর্ট অফলাইনে পাঠানোর ব্যবস্থা করা হয়েছে।",
        offlineSosDispatchedTitle = "SMS মাধ্যমে অফলাইন SOS পাঠানো হয়েছে",
        offlineSosDispatchedDesc = "GPS স্থানাঙ্ক সহ ১১২ নম্বরে জরুরি সংকেত পাঠানো হয়েছে। ইন্টারনেট সক্রিয় হলে ক্লাউডে স্বয়ংক্রিয় সিঙ্ক হবে।",
        cloudSosDispatchedTitle = "জরুরি SOS পাঠানো হয়েছে (ক্লাউড)",
        cloudSosDispatchedDesc = "আপনার GPS স্থানাঙ্ক SDRF / NDMA উদ্ধারকারী দলের নিকট পাঠানো হয়েছে।"
    )

    val NE = AppStrings(
        langCode = "ne",
        telemetryRadarActive = "टेलिमेट्री रडार: सक्रिय",
        appTitle = "भूचेतक",
        appSubtitle = "हिमालयी पहिरो पूर्व चेतावनी र उद्धार",
        rainfall = "वर्षा",
        soilSat = "माटोको ओसिलो",
        sectors = "सेक्टरहरू",
        live = "लाइभ",
        emergencySosTitle = "आपतकालीन SOS प्रेषण",
        emergencySosSubtitle = "SDRF / NDMA लाई एक-ट्याप GNSS प्रसारण",
        sosButtonLabel = "आपतकालीन SOS तुरुन्त पठाउनुहोस्",
        sosButtonSub = "उद्धार टोलीलाई तुरुन्त जीपीएस सतर्कता • अफलाइन SMS बाट पनि सक्रिय",
        transmit = "पठाउनुहोस्",
        triggerSosPrompt = "आपतकालीन SOS पठाउने?",
        sosDescription = "यसले तपाईंको प्रमाणित GPS निर्देशांकहरू सिधै राज्य विपद् व्यवस्थापन र उद्धार टोलीहरूमा पठाउँछ।",
        cancel = "रद्द गर्नुहोस्",
        aiHazardNeuralCore = "एआई पहिरो न्यूरल कोर",
        online = "अनलाइन",
        offline = "अफलाइन",
        aiHazardDescription = "२४ घण्टाको वर्षा र भू-उचाइ मोडेल प्रयोग गरी भिरालो जमिन खस्ने जोखिमको मूल्यांकन गर्नुहोस्।",
        calculateRisk = "जोखिम नाप्नुहोस्",
        doppler = "डपलर",
        regionalHazardFeed = "क्षेत्रीय विपद् सूचना",
        activeAlertsSuffix = "पूर्वी हिमालयमा सक्रिय चेतावनीहरू",
        liveFeedBadge = "लाइभ फिड",
        filterAll = "सबै",
        filterCritical = "गम्भीर",
        filterWarning = "चेतावनी",
        filterAdvisory = "सल्लाह",
        severityCritical = "अति गम्भीर संकट",
        severityHigh = "उच्च जोखिम",
        severityModerate = "मध्यम जोखिम",
        severityLow = "कम जोखिम",
        directiveEvacuate = "🚨 तुरुन्त सुरक्षित स्थानमा जानुहोस्: भिरालो ठाउँबाट टाढा रहनुहोस्",
        directiveHigh = "⚠️ उच्च सतर्कता: जमिन निकै कमजोर छ, पहाडी बाटोमा यात्रा नगर्नुहोस्",
        directiveModerate = "⚡ सतर्क रहनुहोस्: पहाडी कटान र पानीको निकास हेर्नुहोस्",
        directiveLow = "✅ सामान्य: जमिन स्थिर र सुरक्षित छ",
        alertNh10Title = "तीव्र भिरालो अस्थिरता चेतावनी — NH-10",
        alertNh10Desc = "सेवोक-कालिम्पोङ सडकखण्डमा भारी वर्षा। २९ माइल र तीस्ता बजार बीच ढुङ्गा-माटो खसेको छ। रातिको यात्रामा रोक।",
        alertDzonguTitle = "पहिरो तथा सुरक्षित स्थान सर्न चेतावनी — जोङ्गु उपत्यका",
        alertDzonguDesc = "माटोमा पानीको दबाब खतराको सीमाभन्दा माथि (18.5 kPa)। माटोको ओसिलोपन ८६%। तुरुन्त सुरक्षित स्थानमा जानुहोस्।",
        alertHaflongTitle = "मध्यम जोखिम सल्लाह — हाफलोङ करिडोर",
        alertHaflongDesc = "विगत ३ दिनमा १२४ मिमी वर्षा। लुमडिङ-बदरपुर रेलमार्ग नजिकका भिरालो जमिनको निरन्तर अनुगमन भइरहेको छ।",
        rainWatchTitle = "वर्षा निगरानी (Rain Watch)",
        rainWatchSub = "प्रत्यक्ष वर्षा र बादल रडार",
        lastUpdated = "अन्तिम अपडेट",
        radarCoverage = "रडार स्टेशन क्षेत्र",
        hourlyForecast = "२४ घण्टाको वर्षा पूर्वानुमान",
        rainfallTotal = "कुल अनुमानित वर्षा",
        reportScreenTitle = "विपद् घटना प्रतिवेदन",
        reportScreenSub = "मैदानी अवलोकन र GPS प्रेषण",
        step1Title = "स्थान र प्रमाण",
        step2Title = "वर्गीकरण",
        autoDetectLocation = "मेरो स्थान स्वतः पत्ता लगाउनुहोस्",
        detectingLocation = "GPS स्थान खोजिँदै छ...",
        locationFieldLabel = "क्षेत्र / जिल्लाको स्थान",
        locationFieldHint = "उदा. नाम्ची, दक्षिण सिक्किम",
        permDialogTitle = "स्थान (GPS) अनुमति आवश्यक छ",
        permDialogDesc = "तपाईंको पहाडी क्षेत्र पत्ता लगाउन र उद्धार टोली पठाउन भूचेतकलाई GPS अनुमति आवश्यक पर्दछ।",
        grantPermission = "अनुमति दिनुहोस्",
        gpsDisabledTitle = "GPS खोल्नुहोस्",
        gpsDisabledDesc = "तपाईंको फोनको लोकेसन बन्द छ। जिल्ला र निर्देशांकहरू स्वतः भर्न कृपया GPS खोल्नुहोस्।",
        openSettings = "सेटिङ खोल्नुहोस्",
        hazardType = "विपद्को प्रकार",
        severityLevel = "गम्भीरता स्तर",
        describeObservation = "जमिन खसेको, धाँजा फाटेको वा बाटो बन्द भएको विवरण दिनुहोस्",
        transmitReport = "विपद् रिपोर्ट पठाउनुहोस्",
        predictionScreenTitle = "एआई जोखिम मूल्यांकन",
        predictionScreenSub = "भूचेतक XGBoost मोडेल",
        geotechnicalScenarios = "भू-प्राविधिक परिदृश्य",
        scenarioSub = "द्रुत सिमुलेशन छान्नुहोस् वा तल तथ्यांक भर्नुहोस्",
        scenarioCloudburst = "मनसुनी बादल फुट्ने",
        scenarioModerate = "मध्यम पहाडी वर्षा",
        scenarioDry = "सुक्खा पहाडी भिरालो",
        slopeTelemetryHeader = "भिरालो र मौसम विज्ञान टेलिमेट्री",
        elevation = "उचाइ (समुद्र सतहबाट m MSL)",
        slopeAngle = "भिरालोपन कोण (डिग्री °)",
        rainfall1d = "२४ घण्टाको वर्षा (mm)",
        rainfall3d = "३ दिनको संचित वर्षा (mm)",
        rainfall7d = "७ दिनको कुल वर्षा (mm)",
        soilMoisture = "माटोको ओसिलोपन (% sat)",
        lithology = "भूवैज्ञानिक चट्टान समूह (Lithology)",
        landCover = "भूमि आवरण वर्ग (Land Cover)",
        runAssessment = "भू-प्राविधिक जोखिम मूल्यांकन गर्नुहोस्",
        runningInference = "गणना भइरहेको छ...",
        failureProbability = "पहिरो जाने सम्भाव्यता",
        contributingFactors = "मुख्य कारकहरू",
        tabAlerts = "चेतावनी",
        tabMap = "नक्सा",
        tabReport = "रिपोर्ट",
        tabProfile = "प्रोफाइल",
        languageDialogTitle = "भाषा र स्थानीय बोली",
        languageDialogSub = "पूर्वी हिमालय क्षेत्र",
        filterByState = "राज्य / क्षेत्र अनुसार खोज्नुहोस्",
        safetyMonitorActive = "सुरक्षा निगरानी: सक्रिय",
        roleCitizen = "नागरिक",
        soilSatUnit = "संतृप्ति",
        defaultSectorName = "सेक्टर: पूर्वी हिमालय (सिक्किम / असम करिडोर)",
        checkLandslideRiskTitle = "पहिरो जोखिम जाँच गर्नुहोस्",
        checkLandslideRiskDesc = "हालको वर्षा र भिरालो जमिनको आधारमा आफ्नो गाउँ वा यात्रा मार्गको पहिरो जोखिम जाँच गर्नुहोस्।",
        checkMyRiskBtn = "जोखिम जाँच गर्नुहोस्",
        rainRadarBtn = "वर्षा रडार",
        offlineModeCached = "अफलाइन मोड — सुरक्षित डेटा",
        offlineNotice = "अफलाइन — पछिल्लो जोखिम डेटा देखाइएको छ। आपतकालीन SOS र रिपोर्टहरू अफलाइन सन्देश मार्फत पठाइनेछन्।",
        offlineSosDispatchedTitle = "SMS मार्फत अफलाइन SOS पठाइयो",
        offlineSosDispatchedDesc = "GPS निर्देशांक सहित ११२ मा आपतकालीन सन्देश पठाइयो। इन्टरनेट पुनः सुरु हुँदा स्वचालित सिङ्क हुनेछ।",
        cloudSosDispatchedTitle = "आपतकालीन SOS पठाइयो (क्लाउड)",
        cloudSosDispatchedDesc = "तपाईंको GPS टेलिमेट्री SDRF / NDMA उद्धार टोलीलाई पठाइएको छ।"
    )

    val BRX = AppStrings(
        langCode = "brx",
        telemetryRadarActive = "टेलिमेट्री राडार: गोख्रों",
        appTitle = "भूचेतक",
        appSubtitle = "हा खनाय सांग्रांथि आरो आपतकालिन जाथाय खौरां",
        rainfall = "अखा हानाय",
        soilSat = "हा लोमनाय",
        sectors = "ओनसोल",
        live = "लाइभ",
        emergencySosTitle = "गोनांथार SOS सांग्रांथि",
        emergencySosSubtitle = "जिला आरो SDRF नो GPS खौरां थिनहर",
        sosButtonLabel = "गोनांथार SOS थिनहर",
        sosButtonSub = "आपतकालिन हान्जायाव थिनहरनाय • अफलाइन आव SMS बाहाय",
        transmit = "थिनहर",
        triggerSosPrompt = "SOS सांग्रांथि थिनहरगोन?",
        sosDescription = "बेयो नोंथांनि दासिमनि GPS जायगानि खौरां जिला खौरां टीमनो थिनहरगोन। थार आपतकाल आव ल' बाहाय।",
        cancel = "नेवसि",
        aiHazardNeuralCore = "AI खैफोद सिगां-फोरमायनाय",
        online = "अनलाइन",
        offline = "अफलाइन",
        aiHazardDescription = "अखा हानाय आरो हाला खोलोबनि सायाव खैफोद साननाय।",
        calculateRisk = "खैफोद साननाय",
        doppler = "राडार",
        regionalHazardFeed = "ओनसोलनि सांग्रांथि खौरां",
        activeAlertsSuffix = "थांखिनाय सांग्रांथिफोर",
        liveFeedBadge = "लाइभ खौरां",
        filterAll = "गासै",
        filterCritical = "गोख्रों खैफोद",
        filterWarning = "सांग्रांथि",
        filterAdvisory = "मोजाङै नोजोर",
        severityCritical = "गंब्लां खैफोद",
        severityHigh = "गेदेर खैफोद",
        severityModerate = "गेजेर खैफोद",
        severityLow = "खम खैफोद",
        directiveEvacuate = "🚨 गोजौ जायगायाव खारलां: हा खनायनि खैफोद दं",
        directiveHigh = "⚠️ गोख्रों सांग्रां: हाला लामायाव दाथां",
        directiveModerate = "⚡ नोजोर हो: हा सिखारनायखौ सांग्रां था",
        directiveLow = "✅ मोजां: हालाया गोरोबना दं",
        alertNh10Title = "हाला खोलोब खैफोद — NH-10",
        alertNh10Desc = "गोख्रों अखा हानयनि जाहोनाव लामायाव हा खनाय जाथाय जादों। हरनि समाव थांनाया बन्द।",
        alertDzonguTitle = "जोङु भेलि हा खनाय सांग्रांथि",
        alertDzonguDesc = "हायाव दै लोमनाया बांदों (86%)। गोजौ जायगायाव थांनो सांग्रांथि होनाय जाबाय।",
        alertHaflongTitle = "हाफलं लामा सांग्रांथि",
        alertHaflongDesc = "हाफलं रेल लामायाव हा खनाय सांग्रांथि। सानफ्रोमबो नोजोर लाखिनाय जादों।",
        rainWatchTitle = "अखा नायग्रानय (Rain Watch)",
        rainWatchSub = "अखा हानायनि लाइभ राडार",
        lastUpdated = "गोदान खौरां",
        radarCoverage = "राडार ओनसोल",
        hourlyForecast = "घन्टाफानि सिगां-खौरां",
        rainfallTotal = "गासै अखा हानाय",
        reportScreenTitle = "जाथायनि खौरां हो",
        reportScreenSub = "गामी आरो हाला खौरां थिनहर",
        step1Title = "जायगा आरो फोटो",
        step2Title = "खैफोदनि रोखोम",
        autoDetectLocation = "आंनि जायगाखौ दिहुन",
        detectingLocation = "GPS जायगा नागिरदों...",
        locationFieldLabel = "ओनसोल / जिला जायगा",
        locationFieldHint = "जेरै: नामचि, सिक्किम / हाफलं, असम",
        permDialogTitle = "GPS नि हुकुम नांगौ",
        permDialogDesc = "भूचेतक नो जायगा दिहुननो आरो सांग्रांथि थिनहरनो GPS हुकुम नांगौ।",
        grantPermission = "हुकुम हो",
        gpsDisabledTitle = "GPS खौ सालाय",
        gpsDisabledDesc = "नोंथांनि फोननि जायगा बन्द दं। GPS अन खालाम।",
        openSettings = "सेटिं खुलि",
        hazardType = "जाथायनि रोखोम",
        severityLevel = "खैफोदनि गेबेंथि",
        describeObservation = "हा खनाय, लामा बन्द एबा हा बांद्रायनायनि खौरां लिर",
        transmitReport = "खौरां थिनहर",
        predictionScreenTitle = "AI खैफोद सिगां-फोरमायनाय",
        predictionScreenSub = "भूचेतक XGBoost मदेल",
        geotechnicalScenarios = "हा आरो बोथोरनि फाराग",
        scenarioSub = "गोख्रों अखा एबा बारनाय सायख'",
        scenarioCloudburst = "गोख्रों अखा हानाय (Cloudburst)",
        scenarioModerate = "गेजेर अखा हानाय",
        scenarioDry = "गोरान हाला",
        slopeTelemetryHeader = "हाला आरो अखा टेलिमेट्री",
        elevation = "जौथाइ (मिटार MSL)",
        slopeAngle = "हाला खोलोब (°)",
        rainfall1d = "२४ घन्टायाव अखा (मिमि)",
        rainfall3d = "३ साननि अखा (मिमि)",
        rainfall7d = "७ साननि गासै अखा (मिमि)",
        soilMoisture = "हा लोमनाय (% sat)",
        lithology = "अनथायनि रोखोम (Lithology)",
        landCover = "हा रोखोम (Land Cover)",
        runAssessment = "खैफोद साननाय",
        runningInference = "हिसाब खालामगासिनो दङ...",
        failureProbability = "हा खनायनि जाथावना",
        contributingFactors = "गाहाय जाहोनफोर",
        tabAlerts = "सांग्रांथि",
        tabMap = "मानसिबि",
        tabReport = "खौरां",
        tabProfile = "प्रफाइल",
        languageDialogTitle = "राव आरो ओनसोलारि बाहायनाय",
        languageDialogSub = "सानजा हिमालय ओनसोल",
        filterByState = "रायजो / ओनसोल सायख'",
        safetyMonitorActive = "रैखाथि नोजोर: गोख्रों",
        roleCitizen = "सुबुं",
        soilSatUnit = "लोमनाय",
        defaultSectorName = "ओनसोल: सानजा हिमालय (सिक्किम / असम)",
        checkLandslideRiskTitle = "हा खनाय खैफोद नाय",
        checkLandslideRiskDesc = "गावनि गामि एबा लामायाव हा खनायनि खैफोद दं ना गैया नाय।",
        checkMyRiskBtn = "खैफोद नाय",
        rainRadarBtn = "अखा राडार",
        offlineModeCached = "अफलाइन — दोनथुमनाय खौरां",
        offlineNotice = "अफलाइन — नेट गैयिब्लाबो खौरां दिन्थिदों। SOS आरो खौरांखौ फोन आव दोनथुमगोन।",
        offlineSosDispatchedTitle = "SMS जों अफलाइन SOS थिनहरबाय",
        offlineSosDispatchedDesc = "११२ आव GPS जों SMS थिनहरनाय जाबाय। नेट मोनब्ला गावनो सिंक जागोन।",
        cloudSosDispatchedTitle = "क्लाउड आव SOS थिनहरबाय",
        cloudSosDispatchedDesc = "नोंथांनि GPS खौ SDRF / NDMA हान्जायाव थिनहरबाय।"
    )

    val KHA = AppStrings(
        langCode = "kha",
        telemetryRadarActive = "RADAR TELEMETRY: SHONG SYIER",
        appTitle = "BHOOCHETAK",
        appSubtitle = "Jingmaham Twit Khyndew bad Ka Jingiarap Kynsan",
        rainfall = "SLAP",
        soilSat = "KHYNDEW SNGEM",
        sectors = "KI BYNTA",
        live = "Mynta",
        emergencySosTitle = "JINGKYRPAD KYNSAN SOS",
        emergencySosSubtitle = "Phah GPS sha SDRF / NDMA da kaba shon tang shisien",
        sosButtonLabel = "PHAH IA KA SOS KYNSAN MYNTA",
        sosButtonSub = "Phah sha ka SDRF • Trei kam Offline lyngba ka SMS",
        transmit = "PHAH",
        triggerSosPrompt = "PHAH IA KA SOS ALERT?",
        sosDescription = "Kane kan phah ia ka jaka ba phi don ha ka District Emergency Rescue Team bad State Disaster Management Authority.\n\nPyndonkam tang haba don jingsniew kynsan ne jingma ia ka jingim.",
        cancel = "PYNKUT",
        aiHazardNeuralCore = "AI JINGIATHUHLPA IA KA JINGMA",
        online = "ONLINE",
        offline = "OFFLINE",
        aiHazardDescription = "Khein ia ka jingma ba twit khyndew lyngba ka slap 24 kynta, ka jingsngem ka khyndew bad ka jingran ka lum.",
        calculateRisk = "Khein ia ka Jingma",
        doppler = "Radar",
        regionalHazardFeed = "Ki Jingmaham ha ki Dong bapher",
        activeAlertsSuffix = "Ki jingmaham ba mynta ha Eastern Himalayas",
        liveFeedBadge = "Khubor Mynta",
        filterAll = "Baroh",
        filterCritical = "Ba Khraw Tam",
        filterWarning = "Ba Khraw",
        filterAdvisory = "Ba Pdeng",
        severityCritical = "Jingma ba Khraw Tam",
        severityHigh = "Jingma ba Jur",
        severityModerate = "Jingma ba Pdeng",
        severityLow = "Jingma ba Rit",
        directiveEvacuate = "🚨 Phet noh sha kaba shngain: Kiar na ki jaka ba twit khyndew",
        directiveHigh = "⚠️ Maham Jur: Ka khyndew ka la sngem jur, kiar na kaba leit jngai",
        directiveModerate = "⚡ Peitngor: Phikir ia ki thwei bad ki rud lum",
        directiveLow = "✅ Shngain: Ka khyndew ka skhem bha",
        alertNh10Title = "Ka jingma ba twit khyndew — NH-10",
        alertNh10Desc = "Slap jur ha Sevoke-Kalimpong. Twit khyndew ha KM 29 bad Teesta Bazar. Khang ia ka leit ka wan mynmiet.",
        alertDzonguTitle = "Jingmaham phet noh — Dzongu Valley",
        alertDzonguDesc = "Ka jingsngem ka khyndew ka la jur palat (86%). Bthah ban phet sha ki jaka ba shngain.",
        alertHaflongTitle = "Jingmaham ba pdeng — Haflong Corridor",
        alertHaflongDesc = "Slap 124mm ha ki 3 sngi ba la dep. Peitngor ia ki jaka ba marjan bad ka railway line.",
        rainWatchTitle = "Peit ia ka Slap (Rain Watch)",
        rainWatchSub = "Live radar jong ka slap bad ki lyoh",
        lastUpdated = "Pynbna khatduh",
        radarCoverage = "Jaka ba kdup ka radar",
        hourlyForecast = "Jingiathuhlpa slap man ka kynta",
        rainfallTotal = "Ka jinghap slap baroh",
        reportScreenTitle = "Ai burom/kaiphod halor ka jingsniew",
        reportScreenSub = "Phah ia ka jingiohi bad GPS",
        step1Title = "Ka jaka bad ki Dur",
        step2Title = "Jait jingsniew",
        autoDetectLocation = "Shem hi ia ka jaka ba nga don",
        detectingLocation = "Dang wad ia ka GPS...",
        locationFieldLabel = "Kyrteng ka jaka / Distrik",
        locationFieldHint = "Kumba: Namchi, South Sikkim / Shillong, Meghalaya",
        permDialogTitle = "Donkam ia ka GPS Permission",
        permDialogDesc = "Bhoochetak ka donkam ia ka GPS ban shem ia ka jaka ba phi don bad ban phah ia ki lad jingiarap.",
        grantPermission = "Shah ban pyndonkam",
        gpsDisabledTitle = "Pynmeh ia ka GPS",
        gpsDisabledDesc = "Ka GPS jong phi ka la lip. Sngewbha pynmeh ban khein ia ka jaka ba phi don.",
        openSettings = "Plie Settings",
        hazardType = "Jait jingsniew",
        severityLevel = "Ka kyrdan jong ka jingma",
        describeObservation = "Batai bniah halor ka jingtwa khyndew, jingpait ka jaka ne jingsahkut surok",
        transmitReport = "Phah ia ka Kaiphod",
        predictionScreenTitle = "AI Jingiathuhlpa ia ka jingma",
        predictionScreenSub = "Bhoochetak XGBoost Model",
        geotechnicalScenarios = "Ki nuksa bapher jong ka khyndew",
        scenarioSub = "Jied ia ka nuksa ne thep ia ki jingkhein harum",
        scenarioCloudburst = "Slap jur palat (Cloudburst)",
        scenarioModerate = "Slap ba pdeng ha lum",
        scenarioDry = "Khyndew ba rkhiang",
        slopeTelemetryHeader = "Jingran ka lum bad ka slap",
        elevation = "Jingjrong na duriaw (meters MSL)",
        slopeAngle = "Ka jingran ka lum (°)",
        rainfall1d = "Slap 24 kynta (mm)",
        rainfall3d = "Slap 3 sngi (mm)",
        rainfall7d = "Slap 7 sngi baroh (mm)",
        soilMoisture = "Ka jingsngem ka khyndew (% sat)",
        lithology = "Jait mawshun bad mawram (Lithology)",
        landCover = "Ka jinglong ka khyndew (Land Cover)",
        runAssessment = "Khein ia ka Jingma",
        runningInference = "Dang khein ia ka jingma...",
        failureProbability = "Ka lad ban twit khyndew",
        contributingFactors = "Ki daw ba kongsan",
        tabAlerts = "Jingmaham",
        tabMap = "Map",
        tabReport = "Kaiphod",
        tabProfile = "Profile",
        languageDialogTitle = "Ktien bad Jingkren",
        languageDialogSub = "Dong Eastern Himalayas",
        filterByState = "Jied katkum ka State / Dong",
        safetyMonitorActive = "JINGPEITNGOR: SHONG SYIER",
        roleCitizen = "Nongshongshnong",
        soilSatUnit = "Sngem",
        defaultSectorName = "SECTOR: Eastern Himalayas (Sikkim / Assam)",
        checkLandslideRiskTitle = "PEIT IA KA JINGMA TWIT KHYNDEW",
        checkLandslideRiskDesc = "Peit la ka shnong ne ka surok jong phi ka don ha ka jingma ban twit khyndew katkum ka slap ba dang shu dep.",
        checkMyRiskBtn = "Peit ia ka Jingma",
        rainRadarBtn = "Radar Slap",
        offlineModeCached = "OFFLINE MODE — DATA BA LA KYNSHEW",
        offlineNotice = "Offline — Pyni ia ka data ba la ioh khatduh. Ka SOS bad ki report kin leit ynda la don network.",
        offlineSosDispatchedTitle = "LA PHAH IA KA OFFLINE SOS LYNGBA SMS",
        offlineSosDispatchedDesc = "La phah ia ka GPS sha u 112 lyngba ka SMS. Kan auto-sync sha ka SDRF ynda la don internet.",
        cloudSosDispatchedTitle = "LA PHAH IA KA SOS (CLOUD)",
        cloudSosDispatchedDesc = "La phah ia ka GPS sha ki kynhun SDRF / NDMA."
    )

    val MNI = AppStrings(
        langCode = "mni",
        telemetryRadarActive = "তেলিমিত্রী রাদার: চত্থরি",
        appTitle = "ভূচেতক (BHOOCHETAK)",
        appSubtitle = "হিমালয়গী চিংলেপ চেক্সিন-ৱা অমসুং তেংবাং",
        rainfall = "নোং চুবগী চাং",
        soilSat = "লৈবাক্কী অচেংবা",
        sectors = "মফমশিং",
        live = "লাইভ",
        emergencySosTitle = "খুদক্তা তেংবাং SOS থাবা",
        emergencySosSubtitle = "SDRF / NDMA দা খুদক্তা GPS পাউ পীবা",
        sosButtonLabel = "খুদক্তা SOS চেক্সিন-ৱা থাবীয়ু",
        sosButtonSub = "SDRF দা খুদক্তা GPS থাবা • অফলাইনদা SMS না চত্থবা",
        transmit = "থাবীয়ু",
        triggerSosPrompt = "SOS চেক্সিন-ৱা থাগদরা?",
        sosDescription = "মসিনা নহাক্কী GPS লৈফম দিস্ত্রিক ইমার্জেন্সী টিমদা থাগনি। তশেংবা খুদোংথিবদা খক্তা শীজিন্নবীয়ু।",
        cancel = "তোকপীয়ু",
        aiHazardNeuralCore = "AI চিংলেপ চেক্সিন-ৱা খঙহনবা",
        online = "অনলাইন",
        offline = "অফলাইন",
        aiHazardDescription = "নোং চুবগী চাং অমসুং চিংখৈগী এঙ্গেলদা য়ুম্ফম ওইরগা চিংলেপ খুদোংথিবা শিংথাবা।",
        calculateRisk = "খুদোংথিবা শিংথাবা",
        doppler = "রাদার",
        regionalHazardFeed = "মফম অদুগী চেক্সিন-ৱা পাউ",
        activeAlertsSuffix = "হৌজিক লৈরিবা চেক্সিন-ৱাশিং",
        liveFeedBadge = "লাইভ পাউ",
        filterAll = "পুম্নমক",
        filterCritical = "য়াম্না কন্না খুদোংথিনিংঙাই",
        filterWarning = "কন্না খুদোংথিনিংঙাই",
        filterAdvisory = "মচং ওইরবা",
        severityCritical = "য়াম্না কন্না খুদোংথিনিংঙাই",
        severityHigh = "কন্না খুদোংথিনিংঙাই",
        severityModerate = "মচং ওইরবা খুদোংথিবা",
        severityLow = "অরাইবা খুদোংথিবা",
        directiveEvacuate = "🚨 খুদক্তা অৱাংবা মফমদা চত্থোকউ: চিংলেপ থোকপগী খুদোংথিবা লৈরে",
        directiveHigh = "⚠️ কন্না চেক্সিল্লু: লৈবাক চপ চরে, চিংগী লম্বীদা চৎপদা চেক্সিল্লু",
        directiveModerate = "⚡ য়েংশিল্লু: নোং কুপ্না য়েংশিনবীয়ু",
        directiveLow = "✅ নিংথিনা লৈ: লৈবাক চেৎনা লৈরি",
        alertNh10Title = "চিংলেপ থোকপগী চেক্সিন-ৱা — NH-10",
        alertNh10Desc = "সেভোক-কালিম্পোং লম্বীদা নোং কন্না চুরে। কিমি ২৯ দা চিংলেপ থোক্লে। নুমিদাং লম্বী খোঙচৎ থিংলে।",
        alertDzonguTitle = "জোংগু তম্পাক চিংলেপ চেক্সিন-ৱা",
        alertDzonguDesc = "লৈবাক্কী অচেংবা চপ চরে (৮৬%)। অৱাংবা মফমদা চত্থোক্নবা পাউ পীখ্রে।",
        alertHaflongTitle = "হাফলোং লম্বী চেক্সিন-ৱা",
        alertHaflongDesc = "হৌখিবা ৩ নিদা নোং ১২৪ মিমি চুরে। রেলৱে লম্বীদা য়েংশিনবা চত্থরি।",
        rainWatchTitle = "নোং য়েংশিনবা (Rain Watch)",
        rainWatchSub = "লাইভ নোং অমসুং লৈচিল রাদার",
        lastUpdated = "অরোইবা অপদেত",
        radarCoverage = "রাদার মফম",
        hourlyForecast = "পুং খুদিংগী নোং চুবগী পাউ",
        rainfallTotal = "নোং চুবগী অপুনবা চাং",
        reportScreenTitle = "খুদোংথিবগী পাউ পীবা",
        reportScreenSub = "মফম অমসুং GPS পাউ থাগৎপা",
        step1Title = "মফম অমসুং ফোতো",
        step2Title = "খুদোংথিবগী মখল",
        autoDetectLocation = "ঐগী লৈফম মশামক খঙদোকউ",
        detectingLocation = "GPS লৈফম থিদোক্লি...",
        locationFieldLabel = "মফম / দিস্ত্রিক",
        locationFieldHint = "নুক্সী: নামচি, সিক্কিম / ইম্ফাল, মনিপুর",
        permDialogTitle = "GPS অয়াবা নাংই",
        permDialogDesc = "নহাক্কী মফম খঙনবা অমসুং তেংবাং পুরক্নবা ভূচেতকনা GPS অয়াবা মথৌ তাই।",
        grantPermission = "অয়াবা পীবীয়ু",
        gpsDisabledTitle = "GPS থাবীয়ু",
        gpsDisabledDesc = "নহাক্কী ফোনগী GPS থাদোক-উ।",
        openSettings = "সেটিংস হাংদোকউ",
        hazardType = "খুদোংথিবগী মখল",
        severityLevel = "খুদোংথিবগী থাক",
        describeObservation = "চিংলেপ থোকপা, লৈবাক পাম্বদা লম্বী থিংজিনবগী অকুপ্পা মরোল পীবীয়ু",
        transmitReport = "পাউ থাগৎপা",
        predictionScreenTitle = "AI খুদোংথিবগী মাংজৌননা খঙহনবা",
        predictionScreenSub = "ভূচেতক XGBoost মোদেল",
        geotechnicalScenarios = "লৈবাক অমসুং নোং-চিংগী ফীভম",
        scenarioSub = "সিমুলেসন খনবিয়ু নত্রগা মখাদা চাং পীবীয়ু",
        scenarioCloudburst = "নোং কন্না চুরবা (Cloudburst)",
        scenarioModerate = "মচং ওইরবা নোং",
        scenarioDry = "অকংবা চিংখৈ",
        slopeTelemetryHeader = "চিংখৈ অমসুং নোংগী তেলিমিত্রী",
        elevation = "অৱাংবা (মিতর MSL)",
        slopeAngle = "চিংখৈগী এঙ্গেল (°)",
        rainfall1d = "২৪ পুংদা নোং (মিমি)",
        rainfall3d = "৩ নিগী নোং (মিমি)",
        rainfall7d = "৭ নিগী নোং (মিমি)",
        soilMoisture = "লৈবাক্কী অচেংবা (% sat)",
        lithology = "নুংগী মখল (Lithology)",
        landCover = "লমগী মখল (Land Cover)",
        runAssessment = "খুদোংথিবা শিংথাবা",
        runningInference = "হিসাব তৌরি...",
        failureProbability = "চিংলেপ থোকপগী চাং",
        contributingFactors = "মরু ওইবা মরমশিং",
        tabAlerts = "চেক্সিন-ৱা",
        tabMap = "ম্যাপ",
        tabReport = "পাউ পীবা",
        tabProfile = "প্রোফাইল",
        languageDialogTitle = "লোন অমসুং মফমগী ৱাহৈ",
        languageDialogSub = "নোংপোক হিমালয় মফম",
        filterByState = "ষ্টেট / মফমগী মতুং ইন্না খনবিয়ু",
        safetyMonitorActive = "কনবা য়েংশিনবা: চত্থরি",
        roleCitizen = "লৈবাক মীয়াম",
        soilSatUnit = "অচেংবা",
        defaultSectorName = "মফম: নোংপোক হিমালয় (সিক্কিম / অসাম)",
        checkLandslideRiskTitle = "চিংলেপ খুদোংথিবা য়েংউ",
        checkLandslideRiskDesc = "হন্দক নোং চুরবগা চিংলেপ থোকপগী খুদোংথিবা লৈব্রা য়েংউ।",
        checkMyRiskBtn = "খুদোংথিবা য়েংউ",
        rainRadarBtn = "নোং রাদার",
        offlineModeCached = "অফলাইন মোদ — থম্লিবা পাউ",
        offlineNotice = "অফলাইন — অরোইবা পাউ উৎলি। SOS অমসুং পাউশিং ফোনদা থম্লি।",
        offlineSosDispatchedTitle = "SMS না অফলাইন SOS থাখ্রে",
        offlineSosDispatchedDesc = "GPS লৈফমগা লোয়ননা ১১২ দা SMS থাখ্রে। নেত য়ৌরকপদা মশামক সিঙ্ক তৌগনি।",
        cloudSosDispatchedTitle = "ক্লাউদতা SOS থাখ্রে",
        cloudSosDispatchedDesc = "নহাক্কী GPS পাউ SDRF / NDMA তিমদা পীখ্রে।"
    )

    val LUS = AppStrings(
        langCode = "lus",
        telemetryRadarActive = "RADAR TELEMETRY: A THAWK MEK",
        appTitle = "BHOOCHETAK",
        appSubtitle = "Himalayan Leimin Hriattirna & Chhiatrupna Rang Tak",
        rainfall = "RUAH SUR",
        soilSat = "LEI HNAWNG",
        sectors = "HMUNTE",
        live = "Live",
        emergencySosTitle = "CHHIATRUPNA SOS THAWN",
        emergencySosSubtitle = "SDRF / NDMA hnenah vawikhat hmehin GPS thawnna",
        sosButtonLabel = "CHHIATRUPNA SOS THAWN RAWH",
        sosButtonSub = "SDRF hnenah GPS thawn nghalna • Offline-in SMS hmangin a thawk",
        transmit = "THAWN RAWH",
        triggerSosPrompt = "SOS THAWN I DUH EM?",
        sosDescription = "Hei hian i GPS awmna hmun District Disaster Rescue Team leh State Disaster Management Authority hnenah a thawn ang.\n\nHarsatna tak tak leh nunna atan a hlauhawm thilah chauh hman tur a ni.",
        cancel = "SUT LEH RAWH",
        aiHazardNeuralCore = "AI LEIMIN HRILHLAWKNA",
        online = "ONLINE",
        offline = "OFFLINE",
        aiHazardDescription = "Darkar 24 chhunga ruah sur zat leh tlang awn zawng atanga leimin hlauhawm dan chhut chhuahna.",
        calculateRisk = "Hlauhawm Chhut Rawh",
        doppler = "Radar",
        regionalHazardFeed = "Hmun Hrang Hranga Hriattirnate",
        activeAlertsSuffix = "Eastern Himalayas-a hriattirna awm mekte",
        liveFeedBadge = "Chanchin Thar",
        filterAll = "Zawng zawng",
        filterCritical = "Hlauhawm Zual",
        filterWarning = "Hlauhawm Nasa",
        filterAdvisory = "Fimkhurna",
        severityCritical = "Hlauhawm Zualpui",
        severityHigh = "Hlauhawm Nasa",
        severityModerate = "Hlauhawm Pangngai",
        severityLow = "Hlauhawm Lo",
        directiveEvacuate = "🚨 Hmun him lam pan rawh: Leimin hlauhawm a awm e",
        directiveHigh = "⚠️ Fimkhur hle rawh: Lei a hnawng nasa, tlang kawng zawh pumpelh rawh",
        directiveModerate = "⚡ En thlithlai rawh: Tlang pang leh kawngsirte ngaihven rawh",
        directiveLow = "✅ A him: Lei a nghet ṭha e",
        alertNh10Title = "Leimin hlauhawm hriattirna — NH-10",
        alertNh10Desc = "Sevoke-Kalimpong kawngpui-ah ruah a sur nasa. KM 29-ah leimin a awm a, zan kalphung khap a ni.",
        alertDzonguTitle = "Insaseng tura hriattirna — Dzongu Phai",
        alertDzonguDesc = "Lei hnawng zat a sang lutuk (86%). Hmun him zawk pan tura hriattir in ni.",
        alertHaflongTitle = "Fimkhur tura hriattirna — Haflong Corridor",
        alertHaflongDesc = "Ni 3 chhungin ruah 124mm a sur. Railway line bul hnaiahte ngun taka en thlithlai mek a ni.",
        rainWatchTitle = "Ruahsur Enna (Rain Watch)",
        rainWatchSub = "Ruahsur leh chhum awm dan live radar",
        lastUpdated = "Update hnuhnung ber",
        radarCoverage = "Radar Huam Chin",
        hourlyForecast = "Darkar tina khawchin hrilhlawkna",
        rainfallTotal = "Ruahsur zat pumpui",
        reportScreenTitle = "Thil thleng report rawh",
        reportScreenSub = "A hmun leh GPS thawn rawh",
        step1Title = "A Hmun leh Thlalak",
        step2Title = "Chhiatna Chi",
        autoDetectLocation = "Ka awmna zawng nghal rawh",
        detectingLocation = "GPS awmna zawn mek a ni...",
        locationFieldLabel = "Veng / District hming",
        locationFieldHint = "Entirnan: Namchi, Sikkim / Aizawl, Mizoram",
        permDialogTitle = "GPS Permission a ngai",
        permDialogDesc = "Bhoochetak hian i awmna hmun zawn chhuah nan leh chhanhim hna thawh nan GPS phalna a mamawh.",
        grantPermission = "Phalna Pe Rawh",
        gpsDisabledTitle = "GPS Ti Nung Rawh",
        gpsDisabledDesc = "I phone GPS a in-off mek. A hmun zawng chhuak turin GPS ti nung rawh.",
        openSettings = "Settings Hawng Rawh",
        hazardType = "Chhiatna Chi",
        severityLevel = "Hlauhawm Dan Level",
        describeObservation = "Leimin, kawng chhia leh thil thlengte chipchiar takin sawi rawh",
        transmitReport = "Report Thawn Rawh",
        predictionScreenTitle = "AI Leimin Hrilhlawkna",
        predictionScreenSub = "Bhoochetak XGBoost Model",
        geotechnicalScenarios = "Lei leh Khawchin Awm Dan",
        scenarioSub = "A hnuaia mite hi thlang la emaw a data dah lut rawh",
        scenarioCloudburst = "Ruahpui vanawn sur (Cloudburst)",
        scenarioModerate = "Ruahsur pangngai",
        scenarioDry = "Khaw thal / Tlang ro",
        slopeTelemetryHeader = "Tlang awn zawng leh Ruahsur zat",
        elevation = "San lam (meters MSL)",
        slopeAngle = "Tlang awn zawng (°)",
        rainfall1d = "Darkar 24 ruahsur zat (mm)",
        rainfall3d = "Ni 3 ruahsur zat (mm)",
        rainfall7d = "Ni 7 ruahsur zat (mm)",
        soilMoisture = "Lei hnawng zat (% sat)",
        lithology = "Lung chi hrang hrang (Lithology)",
        landCover = "Lei hman dan (Land Cover)",
        runAssessment = "Hlauhawm Chhut Rawh",
        runningInference = "Chhut mek a ni...",
        failureProbability = "Leimin theihna chance",
        contributingFactors = "A chhan lian berte",
        tabAlerts = "Hriattirna",
        tabMap = "Map",
        tabReport = "Report",
        tabProfile = "Profile",
        languageDialogTitle = "Ṭawng leh Hman Dan",
        languageDialogSub = "Eastern Himalayas Huam Chhung",
        filterByState = "State / Hmun mila thlanna",
        safetyMonitorActive = "HIMNA VENGTU: A THAWK MEK",
        roleCitizen = "Khawtlang mi",
        soilSatUnit = "Hnawng",
        defaultSectorName = "SECTOR: Eastern Himalayas (Sikkim / Assam)",
        checkLandslideRiskTitle = "LEIMIN HLAUHAWM EN RAWH",
        checkLandslideRiskDesc = "Ruahsur nasat dan azirin i khua leh kawngte leimin hlauhawmah a awm em tih en rawh.",
        checkMyRiskBtn = "Hlauhawm En Rawh",
        rainRadarBtn = "Ruah Radar",
        offlineModeCached = "OFFLINE MODE — DATA VAWN ṬHAT",
        offlineNotice = "Offline — Chanchin thar ber vawn ṭhat a lang e. SOS leh report-te chu phone-ah vawn a ni a, network awmah a thawn ang.",
        offlineSosDispatchedTitle = "SMS HMANGIN OFFLINE SOS THAWN A NI",
        offlineSosDispatchedDesc = "112 hnenah GPS awmna nen SMS thawn a ni ta. Internet a awm veleh SDRF-ah a in-sync ang.",
        cloudSosDispatchedTitle = "SOS THAWN A NI TA (CLOUD)",
        cloudSosDispatchedDesc = "I GPS awmna SDRF / NDMA hnenah thawn a ni e."
    )

    fun get(code: String): AppStrings {
        return when (code.lowercase()) {
            "hi" -> HI
            "as" -> AS
            "brx" -> BRX
            "kha", "b+kha" -> KHA
            "mni", "b+mni" -> MNI
            "lus" -> LUS
            "ne" -> NE
            "bn" -> BN
            else -> EN
        }
    }
}

val LocalAppStrings = staticCompositionLocalOf<AppStrings> {
    AppStringsRepository.EN
}
