package com.ner.landslide.presentation.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf
import com.ner.landslide.domain.model.Alert
import com.ner.landslide.domain.model.AlertSeverity

/**
 * Reactive localized strings model for Bhurakshak NER 2.0.
 * Directly reacts to locale switches across English, Hindi, Assamese, Bengali, and Nepali.
 */
data class AppStrings(
    val langCode: String,

    // Header & Brand
    val telemetryRadarActive: String,
    val appTitle: String,
    val appSubtitle: String,

    // Telemetry Cards
    val rainfall: String,
    val soilSat: String,
    val sectors: String,
    val live: String,

    // Prominent SOS Hero
    val emergencySosTitle: String,
    val emergencySosSubtitle: String,
    val sosButtonLabel: String,
    val sosButtonSub: String,
    val transmit: String,
    val triggerSosPrompt: String,
    val sosDescription: String,
    val cancel: String,

    // AI Hazard Core
    val aiHazardNeuralCore: String,
    val online: String,
    val offline: String,
    val aiHazardDescription: String,
    val calculateRisk: String,
    val doppler: String,

    // Regional Hazard Feed & Severities
    val regionalHazardFeed: String,
    val activeAlertsSuffix: String,
    val liveFeedBadge: String,
    val filterAll: String,
    val filterCritical: String,
    val filterWarning: String,
    val filterAdvisory: String,
    val severityCritical: String,
    val severityHigh: String,
    val severityModerate: String,
    val severityLow: String,
    val directiveEvacuate: String,
    val directiveHigh: String,
    val directiveModerate: String,
    val directiveLow: String,

    // Default Localized Alert Data
    val alertNh10Title: String,
    val alertNh10Desc: String,
    val alertDzonguTitle: String,
    val alertDzonguDesc: String,
    val alertHaflongTitle: String,
    val alertHaflongDesc: String,

    // Rain Watch Screen (Formerly Doppler)
    val rainWatchTitle: String,
    val rainWatchSub: String,
    val lastUpdated: String,
    val radarCoverage: String,
    val hourlyForecast: String,
    val rainfallTotal: String,

    // Incident Report Screen
    val reportScreenTitle: String,
    val reportScreenSub: String,
    val step1Title: String,
    val step2Title: String,
    val autoDetectLocation: String,
    val detectingLocation: String,
    val locationFieldLabel: String,
    val locationFieldHint: String,
    val permDialogTitle: String,
    val permDialogDesc: String,
    val grantPermission: String,
    val gpsDisabledTitle: String,
    val gpsDisabledDesc: String,
    val openSettings: String,
    val hazardType: String,
    val severityLevel: String,
    val describeObservation: String,
    val transmitReport: String,

    // Prediction Screen
    val predictionScreenTitle: String,
    val predictionScreenSub: String,
    val geotechnicalScenarios: String,
    val scenarioSub: String,
    val scenarioCloudburst: String,
    val scenarioModerate: String,
    val scenarioDry: String,
    val slopeTelemetryHeader: String,
    val elevation: String,
    val slopeAngle: String,
    val rainfall1d: String,
    val rainfall3d: String,
    val rainfall7d: String,
    val soilMoisture: String,
    val lithology: String,
    val landCover: String,
    val runAssessment: String,
    val runningInference: String,
    val failureProbability: String,
    val contributingFactors: String,

    // Navigation Tabs
    val tabAlerts: String,
    val tabMap: String,
    val tabReport: String,
    val tabProfile: String,

    // Language Dialog
    val languageDialogTitle: String,
    val languageDialogSub: String,
    val filterByState: String
)

fun AlertSeverity.toLocalizedLabel(strings: AppStrings): String = when (this) {
    AlertSeverity.CRITICAL -> strings.severityCritical
    AlertSeverity.HIGH -> strings.severityHigh
    AlertSeverity.MODERATE -> strings.severityModerate
    AlertSeverity.LOW -> strings.severityLow
}

fun AlertSeverity.toLocalizedDirective(strings: AppStrings): String = when (this) {
    AlertSeverity.CRITICAL -> strings.directiveEvacuate
    AlertSeverity.HIGH -> strings.directiveHigh
    AlertSeverity.MODERATE -> strings.directiveModerate
    AlertSeverity.LOW -> strings.directiveLow
}

fun Alert.getLocalizedTitle(strings: AppStrings): String = when (this.id) {
    "alert_nh10" -> strings.alertNh10Title
    "alert_dzongu" -> strings.alertDzonguTitle
    "alert_haflong" -> strings.alertHaflongTitle
    else -> this.title
}

fun Alert.getLocalizedDescription(strings: AppStrings): String = when (this.id) {
    "alert_nh10" -> strings.alertNh10Desc
    "alert_dzongu" -> strings.alertDzonguDesc
    "alert_haflong" -> strings.alertHaflongDesc
    else -> this.description
}

object AppStringsRepository {

    val EN = AppStrings(
        langCode = "en",
        telemetryRadarActive = "TELEMETRY RADAR: ACTIVE",
        appTitle = "BHURAKSHAK",
        appSubtitle = "Himalayan Landslide Early Warning & Response",
        rainfall = "RAINFALL",
        soilSat = "SOIL SAT",
        sectors = "SECTORS",
        live = "Live",
        emergencySosTitle = "EMERGENCY SOS DISPATCH",
        emergencySosSubtitle = "One-tap GNSS broadcast to SDRF / NDMA",
        sosButtonLabel = "SEND EMERGENCY SOS NOW",
        sosButtonSub = "Press to alert local rescue teams immediately",
        transmit = "TRANSMIT",
        triggerSosPrompt = "TRIGGER EMERGENCY SOS?",
        sosDescription = "This broadcasts your verified GPS coordinates directly to the State Disaster Management Authority (SDMA) and District Incident Response Teams.\n\nUse solely in case of immediate slope failure, structural collapse, or life hazard.",
        cancel = "CANCEL",
        aiHazardNeuralCore = "AI HAZARD NEURAL CORE",
        online = "ONLINE",
        offline = "OFFLINE",
        aiHazardDescription = "Evaluate geotechnical slope failure probability using live 24h rainfall saturation, antecedent precipitation index, and digital elevation models.",
        calculateRisk = "Calculate Risk",
        doppler = "Doppler",
        regionalHazardFeed = "REGIONAL HAZARD FEED",
        activeAlertsSuffix = "Active Warnings in Eastern Himalayas",
        liveFeedBadge = "LIVE FEED",
        filterAll = "All",
        filterCritical = "Critical",
        filterWarning = "High",
        filterAdvisory = "Moderate",
        severityCritical = "Critical Hazard",
        severityHigh = "High Risk",
        severityModerate = "Moderate Risk",
        severityLow = "Low Risk",
        directiveEvacuate = "🚨 Immediate evacuation recommended: avoid downhill slopes",
        directiveHigh = "⚠️ High alert: soil near saturation, restrict travel on hill passes",
        directiveModerate = "⚡ Watch status: monitor drainage culverts and road cuts",
        directiveLow = "✅ Normal: stable ground conditions within acceptable safety margins",
        alertNh10Title = "Severe Slope Instability Warning — NH-10",
        alertNh10Desc = "Heavy rainfall detected in Sevoke-Kalimpong corridor. Active debris slips between 29th Mile and Teesta Bazar. Night vehicular transit restricted.",
        alertDzonguTitle = "Critical Landslide Evacuation Watch — Dzongu Valley",
        alertDzonguDesc = "Pore water pressure sensors exceeding safety threshold (18.5 kPa). Soil saturation at 86%. Downhill evacuation protocol in effect.",
        alertHaflongTitle = "Moderate Risk Advisory — Haflong Corridor",
        alertHaflongDesc = "Antecedent 3-day rainfall at 124 mm. Hill cutting zones along Lumding-Badarpur railway section under active sensor surveillance.",
        rainWatchTitle = "Rain Watch",
        rainWatchSub = "Live Rain & Cloud Radar",
        lastUpdated = "Last updated",
        radarCoverage = "Radar Station Coverage",
        hourlyForecast = "24-Hour Precipitation Forecast",
        rainfallTotal = "Total Estimated Rain",
        reportScreenTitle = "Incident Report",
        reportScreenSub = "Field Observation & GPS Dispatch",
        step1Title = "Location & Evidence",
        step2Title = "Classification",
        autoDetectLocation = "Auto-Detect My Location",
        detectingLocation = "Detecting GPS location...",
        locationFieldLabel = "Sector / District Location",
        locationFieldHint = "e.g. Namchi, South Sikkim",
        permDialogTitle = "Location Access Required",
        permDialogDesc = "Bhurakshak requires GPS access to detect your exact mountain sector and route rescue teams to your coordinates.",
        grantPermission = "Grant Permission",
        gpsDisabledTitle = "Turn on GPS Location",
        gpsDisabledDesc = "Your phone's location services are currently turned off. Please enable location to automatically fill your district and coordinates.",
        openSettings = "Open Location Settings",
        hazardType = "Hazard Type",
        severityLevel = "Severity Level",
        describeObservation = "Describe ground movement, cracks, or blocked roads",
        transmitReport = "TRANSMIT DISASTER REPORT",
        predictionScreenTitle = "AI Risk Prediction",
        predictionScreenSub = "BhuRakshak XGBoost Model",
        geotechnicalScenarios = "Geotechnical Scenarios",
        scenarioSub = "Pick a quick simulation preset or enter data below",
        scenarioCloudburst = "Monsoon Cloudburst",
        scenarioModerate = "Moderate Hill Shower",
        scenarioDry = "Dry Hill Slope",
        slopeTelemetryHeader = "Slope & Meteorological Telemetry",
        elevation = "Elevation (MSL in meters)",
        slopeAngle = "Slope Inclination (degrees °)",
        rainfall1d = "24-Hour Rainfall (mm)",
        rainfall3d = "3-Day Antecedent Rain (mm)",
        rainfall7d = "7-Day Cumulative Rain (mm)",
        soilMoisture = "Volumetric Soil Moisture (% sat)",
        lithology = "Lithology Group (Bedrock Type)",
        landCover = "Land Cover Classification",
        runAssessment = "RUN GEOTECHNICAL ASSESSMENT",
        runningInference = "Evaluating Geotechnical Physics...",
        failureProbability = "Estimated Failure Probability",
        contributingFactors = "Primary Contributing Factors",
        tabAlerts = "Alerts",
        tabMap = "Map",
        tabReport = "Report",
        tabProfile = "Profile",
        languageDialogTitle = "Language & Dialect",
        languageDialogSub = "Eastern Himalayan Region",
        filterByState = "Filter by State / Region"
    )

    val HI = AppStrings(
        langCode = "hi",
        telemetryRadarActive = "टेलीमेट्री रडार: सक्रिय",
        appTitle = "भूरक्षक",
        appSubtitle = "हिमालयी भूस्खलन पूर्व चेतावनी एवं त्वरित राहत",
        rainfall = "वर्षा",
        soilSat = "मिट्टी नमी",
        sectors = "सेक्टर",
        live = "लाइव",
        emergencySosTitle = "आपातकालीन संकट संदेश (SOS)",
        emergencySosSubtitle = "SDRF / NDMA को एक-टैप जीपीएस प्रसारण",
        sosButtonLabel = "आपातकालीन SOS तुरंत भेजें",
        sosButtonSub = "बचाव दल को तुरंत सूचित करने के लिए दबाएं",
        transmit = "भेजें",
        triggerSosPrompt = "आपातकालीन SOS भेजें?",
        sosDescription = "यह आपके सटीक GPS निर्देशांक सीधे राज्य आपदा प्रबंधन प्राधिकरण और राहत बचाव दलों को भेजता है। केवल आपात स्थिति में उपयोग करें।",
        cancel = "रद्द करें",
        aiHazardNeuralCore = "एआई भूस्खलन जांच कोर",
        online = "ऑनलाइन",
        offline = "ऑफलाइन",
        aiHazardDescription = "24 घंटे की बारिश और ढलान के आधार पर भूस्खलन के खतरे का आकलन करें।",
        calculateRisk = "जोखिम जांचें",
        doppler = "रडार",
        regionalHazardFeed = "क्षेत्रीय आपदा चेतावनी सूचना",
        activeAlertsSuffix = "पूर्वी हिमालय में सक्रिय चेतावनियां",
        liveFeedBadge = "लाइव सूचना",
        filterAll = "सभी",
        filterCritical = "अति गंभीर",
        filterWarning = "उच्च",
        filterAdvisory = "मध्यम",
        severityCritical = "अति गंभीर संकट",
        severityHigh = "उच्च जोखिम",
        severityModerate = "मध्यम जोखिम",
        severityLow = "कम जोखिम",
        directiveEvacuate = "🚨 तुरंत सुरक्षित स्थान पर जाएं: निचली ढलानों से दूर रहें",
        directiveHigh = "⚠️ उच्च सतर्कता: मिट्टी पूरी तरह गीली है, पहाड़ी रास्तों पर यात्रा से बचें",
        directiveModerate = "⚡ नजर रखें: पहाड़ी कटाव और नालों पर ध्यान दें",
        directiveLow = "✅ सामान्य: जमीन स्थिर और सुरक्षित है",
        alertNh10Title = "तीव्र ढलान अस्थिरता चेतावनी — NH-10",
        alertNh10Desc = "सेवोक-कालिम्पोंग मार्ग में भारी बारिश दर्ज। 29वें मील और तीस्ता बाजार के बीच मलबा खिसका। रात का आवागमन प्रतिबंधित।",
        alertDzonguTitle = "गंभीर भूस्खलन निकासी चेतावनी — जोंगु घाटी",
        alertDzonguDesc = "मिट्टी में पानी का दबाव सीमा से अधिक (18.5 kPa)। मिट्टी संतृप्ति 86%। ढलान से सुरक्षित निकासी के निर्देश।",
        alertHaflongTitle = "मध्यम जोखिम सलाह — हाफलोंग कॉरिडोर",
        alertHaflongDesc = "पिछले 3 दिनों में 124 मिमी बारिश। लुमडिंग-बदरपुर रेलवे लाइन के पास पहाड़ी कटाव क्षेत्रों पर सतत निगरानी जारी।",
        rainWatchTitle = "बारिश निगरानी (Rain Watch)",
        rainWatchSub = "लाइव बारिश और बादल रडार",
        lastUpdated = "अंतिम अपडेट",
        radarCoverage = "रडार स्टेशन कवरेज",
        hourlyForecast = "24 घंटे का वर्षा पूर्वानुमान",
        rainfallTotal = "कुल अनुमानित वर्षा",
        reportScreenTitle = "आपदा घटना रिपोर्ट",
        reportScreenSub = "मैदानी अवलोकन एवं जीपीएस प्रेषण",
        step1Title = "स्थान और साक्ष्य",
        step2Title = "वर्गीकरण",
        autoDetectLocation = "मेरा स्थान स्वतः पता करें",
        detectingLocation = "जीपीएस स्थान खोजा जा रहा है...",
        locationFieldLabel = "क्षेत्र / जिला स्थान",
        locationFieldHint = "उदा. नामची, दक्षिण सिक्किम",
        permDialogTitle = "स्थान (GPS) अनुमति आवश्यक है",
        permDialogDesc = "भूरक्षक को आपके पहाड़ी क्षेत्र का पता लगाने और बचाव दल को आपके पास भेजने के लिए जीपीएस अनुमति की आवश्यकता है।",
        grantPermission = "अनुमति दें",
        gpsDisabledTitle = "जीपीएस (GPS) चालू करें",
        gpsDisabledDesc = "आपके फोन का लोकेशन सिस्टम बंद है। कृपया जिले और निर्देशांक स्वतः भरने के लिए जीपीएस चालू करें।",
        openSettings = "लोकेशन सेटिंग्स खोलें",
        hazardType = "आपदा का प्रकार",
        severityLevel = "गंभीरता स्तर",
        describeObservation = "जमीन में दरार, भूस्खलन या सड़क बंद होने का विवरण दें",
        transmitReport = "आपदा रिपोर्ट भेजें",
        predictionScreenTitle = "एआई जोखिम भविष्यवाणी",
        predictionScreenSub = "भूरक्षक XGBoost मॉडल",
        geotechnicalScenarios = "भू-प्राविधिक परिदृश्य",
        scenarioSub = "त्वरित सिमुलेशन चुनें या नीचे डेटा भरें",
        scenarioCloudburst = "बादल फटना (भारी वर्षा)",
        scenarioModerate = "मध्यम पहाड़ी वर्षा",
        scenarioDry = "सूखी पहाड़ी ढलान",
        slopeTelemetryHeader = "ढलान और मौसम विज्ञान टेलीमेट्री",
        elevation = "समुद्र तल से ऊंचाई (मीटर MSL)",
        slopeAngle = "ढलान कोण (डिग्री °)",
        rainfall1d = "24 घंटे की बारिश (मिमी)",
        rainfall3d = "3 दिन की संचित बारिश (मिमी)",
        rainfall7d = "7 दिन की कुल बारिश (मिमी)",
        soilMoisture = "मिट्टी नमी संतृप्ति (% sat)",
        lithology = "भूवैज्ञानिक चट्टान वर्ग (Lithology)",
        landCover = "भूमि आवरण वर्ग (Land Cover)",
        runAssessment = "जोखिम की गणना करें",
        runningInference = "गणना चल रही है...",
        failureProbability = "संभावित भूस्खलन संभावना",
        contributingFactors = "प्रमुख सहायक कारक",
        tabAlerts = "सूचनाएं",
        tabMap = "नक्शा",
        tabReport = "रिपोर्ट",
        tabProfile = "प्रोफाइल",
        languageDialogTitle = "भाषा और बोली",
        languageDialogSub = "पूर्वी हिमालय क्षेत्र",
        filterByState = "राज्य / क्षेत्र अनुसार खोजें"
    )

    val AS = AppStrings(
        langCode = "as",
        telemetryRadarActive = "টেলিমেট্ৰি ৰাডাৰ: সক্ৰিয়",
        appTitle = "ভীৰক্ষক",
        appSubtitle = "হিমালয়ৰ ভূমিস্খলন পূৰ্ব সতৰ্কবাণী আৰু উদ্ধাৰ",
        rainfall = "বৰষুণ",
        soilSat = "মাটিৰ আৰ্দ্ৰতা",
        sectors = "ছেক্টৰ",
        live = "লাইভ",
        emergencySosTitle = "জৰুৰীকালীন SOS প্ৰেৰণ",
        emergencySosSubtitle = "SDRF / NDMA লৈ ১-টেপ GNSS বাৰ্তা",
        sosButtonLabel = "জৰুৰীকালীন SOS এতিয়াই পঠিয়াওক",
        sosButtonSub = "উদ্ধাৰকাৰী দলক তাৎক্ষণিক সতৰ্ক কৰিবলৈ টিপক",
        transmit = "প্ৰেৰণ কৰক",
        triggerSosPrompt = "জৰুৰীকালীন SOS পঠিয়াবনে?",
        sosDescription = "ই আপোনাৰ সঠিক GPS স্থানাংক পোনপটীয়াকৈ ৰাজ্যিক দুৰ্যোগ ব্যৱস্থাপনা আৰু উদ্ধাৰকাৰী দললৈ প্ৰেৰণ কৰিব। কেৱল বিপদৰ সময়ত ব্যৱহাৰ কৰক।",
        cancel = "বাতিল কৰক",
        aiHazardNeuralCore = "এআই ভূমিস্খলন পৰীক্ষা",
        online = "অনলাইন",
        offline = "অফলাইন",
        aiHazardDescription = "২৪ ঘণ্টাৰ বৰষুণ আৰু পাহাৰৰ ঢাল ব্যৱহাৰ কৰি ভূমিস্খলনৰ সম্ভাৱনা গণনা কৰক।",
        calculateRisk = "বিপদ পৰীক্ষা কৰক",
        doppler = "ৰাডাৰ",
        regionalHazardFeed = "আঞ্চলিক দুৰ্যোগ সতৰ্কবাণী",
        activeAlertsSuffix = "পূব হিমালয়ত সক্ৰিয় সতৰ্কবাণী",
        liveFeedBadge = "লাইভ ফিড",
        filterAll = "সকলো",
        filterCritical = "চৰম বিপদ",
        filterWarning = "উচ্চ",
        filterAdvisory = "মজলীয়া",
        severityCritical = "চৰম সংকট",
        severityHigh = "উচ্চ বিপদ",
        severityModerate = "মজলীয়া বিপদ",
        severityLow = "কম বিপদ",
        directiveEvacuate = "🚨 তাৎক্ষণিক সুৰক্ষিত স্থানলৈ যাওক: নিম্ন ঢাল পৰিহাৰ কৰক",
        directiveHigh = "⚠️ উচ্চ সতৰ্কতা: মাটি সম্পূর্ণ তিতিছে, পাহাৰীয়া পথত ভ্ৰমণ নকৰিব",
        directiveModerate = "⚡ সতৰ্ক দৃষ্টি ৰাখক: পাহাৰৰ কাটি লোৱা অংশ আৰু নলা নিৰীক্ষণ কৰক",
        directiveLow = "✅ স্বাভাৱিক: মাটি সুস্থিৰ আৰু সুৰক্ষিত",
        alertNh10Title = "তীব্র ঢাল অস্থিৰতা সতৰ্কবাণী — NH-10",
        alertNh10Desc = "ছেভক-কালিম্পং পথত প্ৰচণ্ড বৰষুণ। ২৯ মাইল আৰু তিস্তা বজাৰৰ মাজত শিল-মাটি খহিছে। ৰাতি যাতায়ত নিষিদ্ধ।",
        alertDzonguTitle = "ভূমিস্খলন আৰু স্থান খালী কৰাৰ সতৰ্কবাণী — জংগু উপত্যকা",
        alertDzonguDesc = "মাটিৰ পানীৰ চাপ বিপদসীমাৰ ওপৰত (18.5 kPa)। মাটিৰ আৰ্দ্ৰতা ৮৬%। সুৰক্ষিত স্থানলৈ যোৱাৰ নিৰ্দেশ।",
        alertHaflongTitle = "মজলীয়া বিপদ পৰামৰ্শ — হাফলং কৰিডৰ",
        alertHaflongDesc = "যোৱা ৩ দিনত ১২৪ মিমি বৰষুণ। লামডিং-বদৰপুৰ ৰে'ল পথৰ কাষৰ পাহাৰীয়া স্থানসমূহ নিৰীক্ষণত ৰখা হৈছে।",
        rainWatchTitle = "বৰষুণ নিৰীক্ষণ (Rain Watch)",
        rainWatchSub = "লাইভ বৰষুণ আৰু ডাৱৰ ৰাডাৰ",
        lastUpdated = "শেহতীয়া আপডেট",
        radarCoverage = "ৰাডাৰ ষ্টেচন এলেকা",
        hourlyForecast = "২৪ ঘণ্টাৰ বৰষুণৰ পূৰ্বানুমান",
        rainfallTotal = "মুঠ সম্ভাৱ্য বৰষুণ",
        reportScreenTitle = "ঘটনাৰ প্ৰতিবেদন",
        reportScreenSub = "ক্ষেত্ৰ নিৰীক্ষণ আৰু GPS প্ৰেৰণ",
        step1Title = "স্থান আৰু তথ্য-প্ৰমাণ",
        step2Title = "শ্ৰেণীবিভাজন",
        autoDetectLocation = "মোৰ স্থান নিজে বিচাৰক",
        detectingLocation = "GPS স্থান বিচৰা হৈছে...",
        locationFieldLabel = "এলেকা / জিলাৰ স্থান",
        locationFieldHint = "উদাহৰণ: নামচি, দক্ষিণ ছিকিম",
        permDialogTitle = "স্থান (GPS) অনুমতিৰ প্ৰয়োজন",
        permDialogDesc = "আপোনাৰ পাহাৰীয়া এলেকা নিৰ্ণয় কৰিবলৈ আৰু উদ্ধাৰকাৰী দল পঠিয়াবলৈ ভূৰক্ষকক GPS অনুমতিৰ প্ৰয়োজন।",
        grantPermission = "অনুমতি দিয়ক",
        gpsDisabledTitle = "GPS স্থান অন কৰক",
        gpsDisabledDesc = "আপোনাৰ ফোনৰ লোকেশ্বন ছিষ্টেম বন্ধ আছে। জিলা আৰু স্থানাংক নিজে পূৰণ কৰিবলৈ অনুগ্ৰহ কৰি GPS অন কৰক।",
        openSettings = "ছেটিংছ খোলক",
        hazardType = "বিপদৰ প্ৰকাৰ",
        severityLevel = "বিপদৰ মাত্ৰা",
        describeObservation = "মাটি খহা, ফাট মেলা বা পথ বন্ধ হোৱাৰ বিৱৰণ দিয়ক",
        transmitReport = "বিপদৰ প্ৰতিবেদন প্ৰেৰণ কৰক",
        predictionScreenTitle = "এআই বিপদ পূৰ্বানুমান",
        predictionScreenSub = "ভূৰক্ষক XGBoost মডেল",
        geotechnicalScenarios = "ভূ-কাৰিকৰী পৰিস্থিতি",
        scenarioSub = "দ্ৰুত পৰীক্ষা বাছনি কৰক বা তলত তথ্য দিয়ক",
        scenarioCloudburst = "মেঘভঙা প্ৰচণ্ড বৰষুণ",
        scenarioModerate = "মজলীয়া পাহাৰীয়া বৰষুণ",
        scenarioDry = "শুকান পাহাৰীয়া ঢাল",
        slopeTelemetryHeader = "ঢাল আৰু বতৰ বিজ্ঞান টেলিমেট্ৰি",
        elevation = "উচ্চতা (সমুদ্ৰপৃষ্ঠৰ পৰা m MSL)",
        slopeAngle = "ঢালৰ কোণ (ডিগ্ৰী °)",
        rainfall1d = "২৪ ঘণ্টাৰ বৰষুণ (mm)",
        rainfall3d = "৩ দিনৰ সঞ্চিত বৰষুণ (mm)",
        rainfall7d = "৭ দিনৰ মুঠ বৰষুণ (mm)",
        soilMoisture = "মাটিৰ আৰ্দ্ৰতা সম্পৃক্তি (% sat)",
        lithology = "ভূতাত্ত্বিক শিলা গোট (Lithology)",
        landCover = "ভূমি আৱৰণ শ্ৰেণী (Land Cover)",
        runAssessment = "বিপদৰ মূল্যাংকন কৰক",
        runningInference = "গণনা চলি আছে...",
        failureProbability = "ঢাল খহি পৰাৰ সম্ভাৱনা",
        contributingFactors = "প্ৰধান কাৰকসমূহ",
        tabAlerts = "সতৰ্কবাণী",
        tabMap = "মানচিত্ৰ",
        tabReport = "প্ৰতিবেদন",
        tabProfile = "প্ৰফাইল",
        languageDialogTitle = "ভাষা আৰু উপভাষা",
        languageDialogSub = "পূব হিমালয় অঞ্চল",
        filterByState = "ৰাজ্য / অঞ্চল অনুসৰি বাছক"
    )

    val BN = AppStrings(
        langCode = "bn",
        telemetryRadarActive = "টেলিমেট্রি রাডার: সক্রিয়",
        appTitle = "ভুরক্ষক",
        appSubtitle = "হিমালয় ভূমিধস পূর্ব সতর্কতা ও উদ্ধার ব্যবস্থা",
        rainfall = "বৃষ্টিপাত",
        soilSat = "মাটির আর্দ্রতা",
        sectors = "সেক্টর",
        live = "লাইভ",
        emergencySosTitle = "জরুরি বিপদ সংকেত (SOS)",
        emergencySosSubtitle = "SDRF / NDMA-তে এক-ট্যাপ জিপিএস সম্প্রচার",
        sosButtonLabel = "জরুরি SOS এখনই পাঠান",
        sosButtonSub = "উদ্ধারকারী দলকে তাৎক্ষণিক সতর্ক করতে চাপুন",
        transmit = "প্রেরণ করুন",
        triggerSosPrompt = "জরুরি SOS পাঠাবেন?",
        sosDescription = "এটি আপনার সুনির্দিষ্ট GPS স্থানাঙ্ক সরাসরি রাজ্য দুর্যোগ ব্যবস্থাপনা ও উদ্ধারকারী দলের কাছে পাঠাবে। কেবল বিপদে ব্যবহার করুন।",
        cancel = "বাতিল",
        aiHazardNeuralCore = "এআই ভূমিধস পর্যবেক্ষণ",
        online = "অনলাইন",
        offline = "অফলাইন",
        aiHazardDescription = "২৪ ঘণ্টার বৃষ্টিপাত ও ঢালু জমির ভিত্তিতে ভূমিধসের ঝুঁকি নির্ণয় করুন।",
        calculateRisk = "ঝুঁকি নির্ণয়",
        doppler = "রাডার",
        regionalHazardFeed = "আঞ্চলিক দুর্যোগ সতর্কতা",
        activeAlertsSuffix = "পূর্ব হিমালয়ে সক্রিয় সতর্কবার্তা",
        liveFeedBadge = "লাইভ ফিড",
        filterAll = "সকল",
        filterCritical = "মারাত্মক",
        filterWarning = "উচ্চ",
        filterAdvisory = "মাঝারি",
        severityCritical = "মারাত্মক সংকট",
        severityHigh = "উচ্চ ঝুঁকি",
        severityModerate = "মাঝারি ঝুঁকি",
        severityLow = "কম ঝুঁকি",
        directiveEvacuate = "🚨 অবিলম্বে নিরাপদ স্থানে যান: ঢালু পথ এড়িয়ে চলুন",
        directiveHigh = "⚠️ উচ্চ সতর্কতা: মাটি অতিরিক্ত স্যাঁতসেঁতে, পাহাড়ি পথে ভ্রমণ এড়িয়ে চলুন",
        directiveModerate = "⚡ নজর রাখুন: পাহাড়ি ফাটল ও ড্রেনেজ পর্যবেক্ষণ করুন",
        directiveLow = "✅ স্বাভাবিক: ভূমি স্থিতিশীল ও নিরাপদ",
        alertNh10Title = "তীব্র ঢাল অস্থিরতার সতর্কতা — NH-10",
        alertNh10Desc = "সেভক-কালিম্পং করিডোরে ভারী বৃষ্টিপাত। ২৯ মাইল ও তিস্তা বাজারের মাঝে পাথর ও মাটি ধস। রাতের যান চলাচল নিষিদ্ধ।",
        alertDzonguTitle = "ভূমিধস ও জরুরি স্থানান্তর সতর্কতা — জংগু উপত্যকা",
        alertDzonguDesc = "মাটির পানির চাপ সহনসীমার বেশি (18.5 kPa)। মাটির আর্দ্রতা ৮৬%। তাৎক্ষণিক নিরাপদে সরে যাওয়ার নির্দেশ।",
        alertHaflongTitle = "মাঝারি ঝুঁকি পরামর্শ — হাফলং করিডোর",
        alertHaflongDesc = "বিগত ৩ দিনে ১২৪ মিমি বৃষ্টিপাত। লামডিং-বদরপুর রেললাইনের নিকটবর্তী পাহাড়ি ধসপ্রবণ এলাকায় নজরদারি চলছে।",
        rainWatchTitle = "বৃষ্টিপাত নজরদারি (Rain Watch)",
        rainWatchSub = "লাইভ বৃষ্টি ও মেঘ রাডার",
        lastUpdated = "সর্বশেষ আপডেট",
        radarCoverage = "রাডার স্টেশন কাভারেজ",
        hourlyForecast = "২৪ ঘণ্টার বৃষ্টিপাতের পূর্বাভাস",
        rainfallTotal = "মোট আনুমানিক বৃষ্টিপাত",
        reportScreenTitle = "দুর্যোগ ঘটনা রিপোর্ট",
        reportScreenSub = "মাঠের পর্যবেক্ষণ ও জিপিএস প্রেরণ",
        step1Title = "স্থান ও তথ্যপ্রমাণ",
        step2Title = "শ্রেণীবিভাগ",
        autoDetectLocation = "আমার অবস্থান স্বয়ংক্রিয়ভাবে খুঁজুন",
        detectingLocation = "জিপিএস অবস্থান খোঁজা হচ্ছে...",
        locationFieldLabel = "এলাকা / জেলার নাম",
        locationFieldHint = "যেমন: নামচি, দক্ষিণ সিকিম",
        permDialogTitle = "অবস্থান (GPS) অনুমতি প্রয়োজন",
        permDialogDesc = "আপনার সঠিক পাহাড়ি অঞ্চল শনাক্ত করতে এবং উদ্ধারকারী দল পাঠাতে ভুরক্ষকের GPS অনুমতি প্রয়োজন।",
        grantPermission = "অনুমতি দিন",
        gpsDisabledTitle = "GPS অবস্থান চালু করুন",
        gpsDisabledDesc = "আপনার ফোনের লোকেশন সার্ভিস বর্তমানে বন্ধ রয়েছে। জেলা ও স্থানাঙ্ক স্বয়ংক্রিয়ভাবে পূরণ করতে GPS চালু করুন।",
        openSettings = "সেটিংস খুলুন",
        hazardType = "বিপদের ধরন",
        severityLevel = "তীব্রতার মাত্রা",
        describeObservation = "মাটি ধস, ফাটল বা রাস্তা অবরুদ্ধ হওয়ার বিবরণ দিন",
        transmitReport = "দুর্যোগ রিপোর্ট প্রেরণ করুন",
        predictionScreenTitle = "এআই ঝুঁকি পূর্বাভাস",
        predictionScreenSub = "ভুরক্ষক XGBoost মডেল",
        geotechnicalScenarios = "ভূ-প্রকৌশল পরিস্থিতি",
        scenarioSub = "দ্রুত সিমুলেশন প্রিসেট বাছুন অথবা নিচে ডেটা লিখুন",
        scenarioCloudburst = "মৌসুমি মেঘভাঙা বৃষ্টি",
        scenarioModerate = "মাঝারি পাহাড়ী বৃষ্টি",
        scenarioDry = "শুকনো পাহাড়ী ঢাল",
        slopeTelemetryHeader = "ঢাল ও আবহাওয়া টেলিমেট্রি",
        elevation = "উচ্চতা (সমুদ্রপৃষ্ঠ থেকে m MSL)",
        slopeAngle = "ঢাল কোণ (ডিগ্রী °)",
        rainfall1d = "২৪ ঘণ্টার বৃষ্টিপাত (mm)",
        rainfall3d = "৩ দিনের পূর্ববর্তী বৃষ্টি (mm)",
        rainfall7d = "৭ দিনের মোট বৃষ্টি (mm)",
        soilMoisture = "মাটির আর্দ্রতা সম্পৃক্তি (% sat)",
        lithology = "ভূতাত্ত্বিক শিলা গ্রুপ (Lithology)",
        landCover = "ভূমি আচ্ছাদন (Land Cover)",
        runAssessment = "ভূ-কারিগরি ঝুঁকি মূল্যায়ন চালান",
        runningInference = "পূর্বাভাস চলছে...",
        failureProbability = "ঢাল ধসের আনুমানিক সম্ভাবনা",
        contributingFactors = "গুরুত্বপূর্ণ কারণসমূহ",
        tabAlerts = "সতর্কতা",
        tabMap = "মানচিত্র",
        tabReport = "প্রতিবেদন",
        tabProfile = "প্রোফাইল",
        languageDialogTitle = "ভাষা ও উপভাষা",
        languageDialogSub = "পূর্ব হিমালয় টেলিমেট্রি",
        filterByState = "রাজ্য / অঞ্চল অনুসারে ফিল্টার করুন"
    )

    val NE = AppStrings(
        langCode = "ne",
        telemetryRadarActive = "टेलिमेट्री रडार: सक्रिय",
        appTitle = "भूरक्षक",
        appSubtitle = "हिमालयी पहिरो पूर्व चेतावनी र उद्धार",
        rainfall = "वर्षा",
        soilSat = "माटोको ओसिलो",
        sectors = "सेक्टरहरू",
        live = "लाइभ",
        emergencySosTitle = "आपतकालीन SOS प्रेषण",
        emergencySosSubtitle = "SDRF / NDMA लाई एक-ट्याप GNSS प्रसारण",
        sosButtonLabel = "आपतकालीन SOS तुरुन्त पठाउनुहोस्",
        sosButtonSub = "उद्धार टोलीलाई तुरुन्त सतर्क गराउन थिच्नुहोस्",
        transmit = "पठाउनुहोस्",
        triggerSosPrompt = "आपतकालीन SOS पठाउने?",
        sosDescription = "यसले तपाईंको प्रमाणित GPS निर्देशांकहरू सिधै राज्य विपद् व्यवस्थापन र उद्धार टोलीहरूमा पठाउँछ।",
        cancel = "रद्द गर्नुहोस्",
        aiHazardNeuralCore = "एआई पहिरो न्यूरल कोर",
        online = "अनलाइन",
        offline = "अफलाइन",
        aiHazardDescription = "२४ घण्टाको वर्षा र भू-उचाइ मोडेल प्रयोग गरी भिरालो जमिन खस्ने जोखिमको मूल्यांकन गर्नुहोस्।",
        calculateRisk = "जोखिम नाप्नुहोस्",
        doppler = "डपलर",
        regionalHazardFeed = "क्षेत्रीय विपद् सूचना",
        activeAlertsSuffix = "पूर्वी हिमालयमा सक्रिय चेतावनीहरू",
        liveFeedBadge = "लाइभ फिड",
        filterAll = "सबै",
        filterCritical = "गम्भीर",
        filterWarning = "चेतावनी",
        filterAdvisory = "सल्लाह",
        severityCritical = "अति गम्भीर संकट",
        severityHigh = "उच्च जोखिम",
        severityModerate = "मध्यम जोखिम",
        severityLow = "कम जोखिम",
        directiveEvacuate = "🚨 तुरुन्त सुरक्षित स्थानमा जानुहोस्: भिरालो ठाउँबाट टाढा रहनुहोस्",
        directiveHigh = "⚠️ उच्च सतर्कता: जमिन निकै कमजोर छ, पहाडी बाटोमा यात्रा नगर्नुहोस्",
        directiveModerate = "⚡ सतर्क रहनुहोस्: पहाडी कटान र पानीको निकास हेर्नुहोस्",
        directiveLow = "✅ सामान्य: जमिन स्थिर र सुरक्षित छ",
        alertNh10Title = "तीव्र भिरालो अस्थिरता चेतावनी — NH-10",
        alertNh10Desc = "सेवोक-कालिम्पोङ सडकखण्डमा भारी वर्षा। २९ माइल र तीस्ता बजार बीच ढुङ्गा-माटो खसेको छ। रातिको यात्रामा रोक।",
        alertDzonguTitle = "पहिरो तथा सुरक्षित स्थान सर्न चेतावनी — जोङ्गु उपत्यका",
        alertDzonguDesc = "माटोमा पानीको दबाब खतराको सीमाभन्दा माथि (18.5 kPa)। माटोको ओसिलोपन ८६%। तुरुन्त सुरक्षित स्थानमा जानुहोस्।",
        alertHaflongTitle = "मध्यम जोखिम सल्लाह — हाफलोङ करिडोर",
        alertHaflongDesc = "विगत ३ दिनमा १२४ मिमी वर्षा। लुमडिङ-बदरपुर रेलमार्ग नजिकका भिरालो जमिनको निरन्तर अनुगमन भइरहेको छ।",
        rainWatchTitle = "वर्षा निगरानी (Rain Watch)",
        rainWatchSub = "प्रत्यक्ष वर्षा र बादल रडार",
        lastUpdated = "अन्तिम अपडेट",
        radarCoverage = "रडार स्टेशन क्षेत्र",
        hourlyForecast = "२४ घण्टाको वर्षा पूर्वानुमान",
        rainfallTotal = "कुल अनुमानित वर्षा",
        reportScreenTitle = "विपद् घटना प्रतिवेदन",
        reportScreenSub = "मैदानी अवलोकन र GPS प्रेषण",
        step1Title = "स्थान र प्रमाण",
        step2Title = "वर्गीकरण",
        autoDetectLocation = "मेरो स्थान स्वतः पत्ता लगाउनुहोस्",
        detectingLocation = "GPS स्थान खोजिँदै छ...",
        locationFieldLabel = "क्षेत्र / जिल्लाको स्थान",
        locationFieldHint = "उदा. नाम्ची, दक्षिण सिक्किम",
        permDialogTitle = "स्थान (GPS) अनुमति आवश्यक छ",
        permDialogDesc = "तपाईंको पहाडी क्षेत्र पत्ता लगाउन र उद्धार टोली पठाउन भूरक्षकलाई GPS अनुमति आवश्यक पर्दछ।",
        grantPermission = "अनुमति दिनुहोस्",
        gpsDisabledTitle = "GPS खोल्नुहोस्",
        gpsDisabledDesc = "तपाईंको फोनको लोकेसन बन्द छ। जिल्ला र निर्देशांकहरू स्वतः भर्न कृपया GPS खोल्नुहोस्।",
        openSettings = "सेटिङ खोल्नुहोस्",
        hazardType = "विपद्को प्रकार",
        severityLevel = "गम्भीरता स्तर",
        describeObservation = "जमिन खसेको, धाँजा फाटेको वा बाटो बन्द भएको विवरण दिनुहोस्",
        transmitReport = "विपद् रिपोर्ट पठाउनुहोस्",
        predictionScreenTitle = "एआई जोखिम मूल्यांकन",
        predictionScreenSub = "भूरक्षक XGBoost मोडेल",
        geotechnicalScenarios = "भू-प्राविधिक परिदृश्य",
        scenarioSub = "द्रुत सिमुलेशन छान्नुहोस् वा तल तथ्यांक भर्नुहोस्",
        scenarioCloudburst = "मनसुनी बादल फुट्ने",
        scenarioModerate = "मध्यम पहाडी वर्षा",
        scenarioDry = "सुक्खा पहाडी भिरालो",
        slopeTelemetryHeader = "भिरालो र मौसम विज्ञान टेलिमेट्री",
        elevation = "उचाइ (समुद्र सतहबाट m MSL)",
        slopeAngle = "भिरालोपन कोण (डिग्री °)",
        rainfall1d = "२४ घण्टाको वर्षा (mm)",
        rainfall3d = "३ दिनको संचित वर्षा (mm)",
        rainfall7d = "७ दिनको कुल वर्षा (mm)",
        soilMoisture = "माटोको ओसिलोपन (% sat)",
        lithology = "भूवैज्ञानिक चट्टान समूह (Lithology)",
        landCover = "भूमि आवरण वर्ग (Land Cover)",
        runAssessment = "भू-प्राविधिक जोखिम मूल्यांकन गर्नुहोस्",
        runningInference = "गणना भइरहेको छ...",
        failureProbability = "पहिरो जाने सम्भाव्यता",
        contributingFactors = "मुख्य कारकहरू",
        tabAlerts = "चेतावनी",
        tabMap = "नक्सा",
        tabReport = "रिपोर्ट",
        tabProfile = "प्रोफाइल",
        languageDialogTitle = "भाषा र स्थानीय बोली",
        languageDialogSub = "पूर्वी हिमालय क्षेत्र",
        filterByState = "राज्य / क्षेत्र अनुसार खोज्नुहोस्"
    )

    fun get(code: String): AppStrings {
        return when (code.lowercase()) {
            "hi" -> HI
            "as" -> AS
            "bn" -> BN
            "ne" -> NE
            else -> EN
        }
    }
}

val LocalAppStrings = staticCompositionLocalOf<AppStrings> {
    AppStringsRepository.EN
}
