package com.ner.landslide.presentation.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf

/**
 * Reactive localized strings model for Bhurakshak NER 2.0.
 * Directly reacts to locale switches across English, Hindi, Assamese, Bengali, Nepali, etc.
 */
data class AppStrings(
    val langCode: String,
    // Header & Brand
    val telemetryRadarActive: String,
    val appTitle: String,
    val appSubtitle: String,

    // Telemetry Cards
    val rainfall: String,
    val soilSat: String,
    val sectors: String,
    val live: String,

    // SOS
    val emergencySosTitle: String,
    val emergencySosSubtitle: String,
    val transmit: String,
    val triggerSosPrompt: String,
    val sosDescription: String,
    val cancel: String,

    // AI Hazard Core
    val aiHazardNeuralCore: String,
    val online: String,
    val aiHazardDescription: String,
    val calculateRisk: String,
    val doppler: String,

    // Regional Hazard Feed
    val regionalHazardFeed: String,
    val activeAlertsSuffix: String,
    val liveFeedBadge: String,
    val filterAll: String,
    val filterCritical: String,
    val filterWarning: String,
    val filterAdvisory: String,

    // Prediction Screen
    val predictionScreenTitle: String,
    val predictionScreenSub: String,
    val geotechnicalScenarios: String,
    val scenarioSub: String,
    val scenarioCloudburst: String,
    val scenarioModerate: String,
    val scenarioDry: String,
    val slopeTelemetryHeader: String,
    val elevation: String,
    val slopeAngle: String,
    val rainfall1d: String,
    val rainfall3d: String,
    val rainfall7d: String,
    val soilMoisture: String,
    val lithology: String,
    val landCover: String,
    val runAssessment: String,
    val runningInference: String,
    val failureProbability: String,
    val contributingFactors: String,

    // Navigation Tabs
    val tabAlerts: String,
    val tabMap: String,
    val tabReport: String,
    val tabProfile: String,

    // Language Dialog
    val languageDialogTitle: String,
    val languageDialogSub: String,
    val filterByState: String
)

object AppStringsRepository {

    val EN = AppStrings(
        langCode = "en",
        telemetryRadarActive = "TELEMETRY RADAR: ACTIVE",
        appTitle = "BHURAKSHAK",
        appSubtitle = "Himalayan Landslide Early Warning & Response",
        rainfall = "RAINFALL",
        soilSat = "SOIL SAT",
        sectors = "SECTORS",
        live = "Live",
        emergencySosTitle = "EMERGENCY SOS DISPATCH",
        emergencySosSubtitle = "One-tap GNSS broadcast to SDRF / NDMA",
        transmit = "TRANSMIT",
        triggerSosPrompt = "TRIGGER EMERGENCY SOS?",
        sosDescription = "This broadcasts your verified GPS coordinates directly to the State Disaster Management Authority (SDMA) and District Incident Response Teams.\n\nUse solely in case of immediate slope failure, structural collapse, or life hazard.",
        cancel = "CANCEL",
        aiHazardNeuralCore = "AI HAZARD NEURAL CORE",
        online = "ONLINE",
        aiHazardDescription = "Evaluate geotechnical slope failure probability using live 24h rainfall saturation, antecedent precipitation index, and digital elevation models.",
        calculateRisk = "Calculate Risk",
        doppler = "Doppler",
        regionalHazardFeed = "Regional Hazard Feed",
        activeAlertsSuffix = "active alert(s) across Eastern Himalayas",
        liveFeedBadge = "LIVE FEED",
        filterAll = "All",
        filterCritical = "Critical",
        filterWarning = "Warning",
        filterAdvisory = "Advisory",
        predictionScreenTitle = "AI Hazard Inference",
        predictionScreenSub = "Geotechnical XGBoost & ML Pipeline",
        geotechnicalScenarios = "Geotechnical Scenarios",
        scenarioSub = "Select a rapid simulation preset or input field telemetry below",
        scenarioCloudburst = "Monsoon Cloudburst",
        scenarioModerate = "Moderate Hill Shower",
        scenarioDry = "Dry Hill Slope",
        slopeTelemetryHeader = "SLOPE & METEOROLOGICAL TELEMETRY",
        elevation = "Elevation (MSL)",
        slopeAngle = "Slope Angle Inclination",
        rainfall1d = "Current 24h Precipitation",
        rainfall3d = "3-Day Antecedent Rainfall Index",
        rainfall7d = "7-Day Cumulative Rainfall",
        soilMoisture = "Volumetric Soil Moisture",
        lithology = "Lithology Group (GLiM Geological Base)",
        landCover = "Land Cover (ESA WorldCover)",
        runAssessment = "RUN GEOTECHNICAL RISK ASSESSMENT",
        runningInference = "RUNNING INFERENCE PIPELINE...",
        failureProbability = "Estimated Slope Failure Probability",
        contributingFactors = "Contributing Geotechnical Factors",
        tabAlerts = "Alerts",
        tabMap = "Map",
        tabReport = "Report",
        tabProfile = "Profile",
        languageDialogTitle = "Language & Dialect",
        languageDialogSub = "Eastern Himalayas Field Telemetry",
        filterByState = "FILTER BY REGION / STATE"
    )

    val HI = AppStrings(
        langCode = "hi",
        telemetryRadarActive = "टेलीमेट्री रडार: सक्रिय",
        appTitle = "भूरक्षक",
        appSubtitle = "हिमालयी भूस्खलन पूर्व चेतावनी और त्वरित प्रतिक्रिया",
        rainfall = "वर्षा",
        soilSat = "मिट्टी नमी",
        sectors = "सेक्टर",
        live = "सक्रिय",
        emergencySosTitle = "आपातकालीन SOS प्रेषण",
        emergencySosSubtitle = "एसडीआरएफ / एनडीएमए को एक-टैप जीएनएसएस प्रसारण",
        transmit = "भेजें",
        triggerSosPrompt = "आपातकालीन SOS भेजें?",
        sosDescription = "यह आपके सत्यापित जीपीएस निर्देशांक सीधे राज्य आपदा प्रबंधन प्राधिकरण (SDMA) और त्वरित प्रतिक्रिया टीमों को प्रसारित करता है।\n\nकेवल तत्काल भूस्खलन या जीवन संकट में ही उपयोग करें।",
        cancel = "रद्द करें",
        aiHazardNeuralCore = "एआई भूस्खलन न्यूरल कोर",
        online = "ऑनलाइन",
        aiHazardDescription = "24 घंटे की वर्षा, पूर्व संचित वर्षा सूचकांक और डिजिटल एलिवेशन मॉडल का उपयोग करके ढलान विफलता की संभावना का मूल्यांकन करें।",
        calculateRisk = "जोखिम गणना करें",
        doppler = "डॉपलर रडार",
        regionalHazardFeed = "क्षेत्रीय आपदा चेतावनी फ़ीड",
        activeAlertsSuffix = "पूर्वी हिमालय में सक्रिय चेतावनियाँ",
        liveFeedBadge = "लाइव फ़ीड",
        filterAll = "सभी",
        filterCritical = "गंभीर",
        filterWarning = "चेतावनी",
        filterAdvisory = "सलाह",
        predictionScreenTitle = "एआई जोखिम पूर्वानुमान",
        predictionScreenSub = "भू-तकनीकी XGBoost एवं मशीन लर्निंग पाइपलाइन",
        geotechnicalScenarios = "भू-तकनीकी परिदृश्य",
        scenarioSub = "त्वरित सिमुलेशन प्रीसेट चुनें या नीचे फ़ील्ड डेटा दर्ज करें",
        scenarioCloudburst = "मानसूनी बादल फटना",
        scenarioModerate = "मध्यम पहाड़ी वर्षा",
        scenarioDry = "सूखा पहाड़ी ढलान",
        slopeTelemetryHeader = "ढलान एवं मौसम विज्ञान टेलीमेट्री",
        elevation = "ऊंचाई (समुद्र तल से m MSL)",
        slopeAngle = "ढाल कोण (झुकाव डिग्री °)",
        rainfall1d = "वर्तमान 24 घंटे की वर्षा (mm)",
        rainfall3d = "3-दिवसीय पूर्व संचित वर्षा (mm)",
        rainfall7d = "7-दिवसीय कुल संचित वर्षा (mm)",
        soilMoisture = "मिट्टी की नमी संतृप्ति (% sat)",
        lithology = "भूवैज्ञानिक शैल समूह (Lithology Group)",
        landCover = "भूमि आवरण वर्ग (Land Cover)",
        runAssessment = "भू-तकनीकी जोखिम मूल्यांकन चलाएं",
        runningInference = "पूर्वानुमान चलाया जा रहा है...",
        failureProbability = "ढलान विफलता की अनुमानित संभावना",
        contributingFactors = "योगदान देने वाले भू-तकनीकी कारक",
        tabAlerts = "चेतावनियाँ",
        tabMap = "मानचित्र",
        tabReport = "रिपोर्ट",
        tabProfile = "प्रोफ़ाइल",
        languageDialogTitle = "भाषा एवं स्थानीय बोली",
        languageDialogSub = "पूर्वी हिमालयी क्षेत्रीय टेलीमेट्री",
        filterByState = "राज्य / क्षेत्र द्वारा फ़िल्टर करें"
    )

    val AS = AppStrings(
        langCode = "as",
        telemetryRadarActive = "টেলিমেট্ৰি ৰাডাৰ: সক্ৰিয়",
        appTitle = "ভুৰক্ষক",
        appSubtitle = "হিমালয়ৰ ভূমিধস আগতীয়া সতৰ্কতা আৰু সঁহাৰি",
        rainfall = "বৰষুণ",
        soilSat = "মাটি সংপৃক্তি",
        sectors = "খণ্ডসমূহ",
        live = "সক্ৰিয়",
        emergencySosTitle = "জৰুৰীকালীন SOS প্ৰেৰণ",
        emergencySosSubtitle = "SDRF / NDMA লৈ তাৎক্ষণিক GNSS সম্প্ৰচাৰ",
        transmit = "প্ৰেৰণ কৰক",
        triggerSosPrompt = "জৰুৰীকালীন SOS প্ৰেৰণ কৰিবনে?",
        sosDescription = "ই আপোনাৰ পৰীক্ষিত GPS স্থান পোনে পোনে দুৰ্যোগ ব্যৱস্থাপনা কৰ্তৃপক্ষলৈ প্ৰেৰণ কৰিব। কেৱল প্ৰকৃত জৰুৰীকালীন অৱস্থাত ব্যৱহাৰ কৰক।",
        cancel = "বাতিল কৰক",
        aiHazardNeuralCore = "এআই বিপদ নিউৰেল ক\'ৰ",
        online = "অনলাইন",
        aiHazardDescription = "২৪ ঘণ্টাৰ বৰষুণ, পূৰ্বৱৰ্তী বৰষুণ আৰু ভূ-উচ্চতা মডেল ব্যৱহাৰ কৰি পাহাৰীয়া ঢাল খহি পৰাৰ সম্ভাৱনা গণনা কৰক।",
        calculateRisk = "বিপদ গণনা কৰক",
        doppler = "ডপলাৰ",
        regionalHazardFeed = "আঞ্চলিক দুৰ্যোগ সতৰ্কবাণী",
        activeAlertsSuffix = "পূব হিমালয়ত সক্ৰিয় সতৰ্কতা",
        liveFeedBadge = "লাইভ ফিড",
        filterAll = "সকলো",
        filterCritical = "গুৰুতৰ",
        filterWarning = "সতৰ্কবাণী",
        filterAdvisory = "পৰামৰ্শ",
        predictionScreenTitle = "এআই বিপদ পূৰ্বানুমান",
        predictionScreenSub = "ভুৰক্ষক XGBoost আৰু মেচিন লাৰ্নিং পাইপলাইন",
        geotechnicalScenarios = "ভূ-কাৰিকৰী পৰিস্থিতি",
        scenarioSub = "দ্ৰুত অনুৰূপকৰণ বাছক অথবা তলত তথ্য প্ৰৱেশ কৰক",
        scenarioCloudburst = "বাৰিষাৰ মেঘ বিস্ফোৰণ",
        scenarioModerate = "মধ্যমীয়া পাহাৰীয়া বৰষুণ",
        scenarioDry = "শুকান পাহাৰৰ ঢাল",
        slopeTelemetryHeader = "ঢাল আৰু বতৰ বিজ্ঞান টেলিমেট্ৰি",
        elevation = "উচ্চতা (সমুদ্ৰ পৃষ্ঠৰ পৰা m MSL)",
        slopeAngle = "ঢাল কোণ (ডিগ্ৰী °)",
        rainfall1d = "বৰ্তমান ২৪ ঘণ্টাৰ বৰষুণ (mm)",
        rainfall3d = "৩-দিনৰ পূৰ্বৱৰ্তী বৰষুণ (mm)",
        rainfall7d = "৭-দিনৰ সঞ্চিত বৰষুণ (mm)",
        soilMoisture = "মাটিৰ আৰ্দ্ৰতা সংপৃক্তি (% sat)",
        lithology = "ভূতাত্ত্বিক শিলৰ গোট (Lithology Lookup)",
        landCover = "ভূমিৰ আৱৰণ (Land Cover Lookup)",
        runAssessment = "ভূ-কাৰিকৰী বিপদ মূল্যায়ন কৰক",
        runningInference = "পূৰ্বানুমান চলি আছে...",
        failureProbability = "ঢাল খহি পৰাৰ আনুমানিক সম্ভাৱনা",
        contributingFactors = "অৰিহণা যোগোৱা কাৰকসমূহ",
        tabAlerts = "সতৰ্কতা",
        tabMap = "মানচিত্ৰ",
        tabReport = "প্ৰতিবেদন",
        tabProfile = "প্ৰ\'ফাইল",
        languageDialogTitle = "ভাষা আৰু উপভাষা",
        languageDialogSub = "পূব হিমালয় অঞ্চল",
        filterByState = "ৰাজ্য / অঞ্চল অনুসৰি বাছক"
    )

    val BN = AppStrings(
        langCode = "bn",
        telemetryRadarActive = "টেলিমেট্রি রাডার: সক্রিয়",
        appTitle = "ভূরক্ষক",
        appSubtitle = "হিমালয় ভূমিধস প্রারম্ভিক সতর্কতা ও প্রতিক্রিয়া",
        rainfall = "বৃষ্টিপাত",
        soilSat = "মাটির আর্দ্রতা",
        sectors = "সেক্টর",
        live = "লাইভ",
        emergencySosTitle = "জরুরী SOS প্রেরণ",
        emergencySosSubtitle = "SDRF / NDMA-তে তাত্ক্ষণিক GPS সম্প্রচার",
        transmit = "প্রেরণ করুন",
        triggerSosPrompt = "জরুরী SOS পাঠাবেন?",
        sosDescription = "এটি আপনার সঠিক GPS অবস্থান সরাসরি দুর্যোগ প্রতিক্রিয়া দলের কাছে পাঠাবে। কেবলমাত্র প্রকৃত জরুরি পরিস্থিতিতে ব্যবহার করুন।",
        cancel = "বাতিল",
        aiHazardNeuralCore = "এআই ভূমিধস নিউরাল কোর",
        online = "অনলাইন",
        aiHazardDescription = "২৪ ঘণ্টার বৃষ্টিপাত, পূর্ববর্তী বৃষ্টিপাত এবং উচ্চতা মডেল বিশ্লেষণ করে ঢাল ধসের ঝুঁকি নির্ণয় করুন।",
        calculateRisk = "ঝুঁকি গণনা করুন",
        doppler = "ডপলার",
        regionalHazardFeed = "আঞ্চলিক দুর্যোগ ফিড",
        activeAlertsSuffix = "পূর্ব হিমালয়ে সক্রিয় সতর্কতা",
        liveFeedBadge = "লাইভ ফিড",
        filterAll = "সকল",
        filterCritical = "গুরুতর",
        filterWarning = "সতর্কতা",
        filterAdvisory = "পরামর্শ",
        predictionScreenTitle = "এআই ঝুঁকি পূর্বাভাস",
        predictionScreenSub = "ভূরক্ষক XGBoost মেশিন লার্নিং পাইপলাইন",
        geotechnicalScenarios = "ভূ-কারিগরি পরিস্থিতি",
        scenarioSub = "দ্রুত সিমুলেশন প্রিসেট বাছুন অথবা নিচে ডেটা লিখুন",
        scenarioCloudburst = "মৌসুমি মেঘভাঙা বৃষ্টি",
        scenarioModerate = "মাঝারি পাহাড়ী বৃষ্টি",
        scenarioDry = "শুকনো পাহাড়ী ঢাল",
        slopeTelemetryHeader = "ঢাল ও আবহাওয়া টেলিমেট্রি",
        elevation = "উচ্চতা (সমুদ্রপৃষ্ঠ থেকে m MSL)",
        slopeAngle = "ঢাল কোণ (ডিগ্রী °)",
        rainfall1d = "২৪ ঘণ্টার বৃষ্টিপাত (mm)",
        rainfall3d = "৩ দিনের পূর্ববর্তী বৃষ্টি (mm)",
        rainfall7d = "৭ দিনের মোট বৃষ্টি (mm)",
        soilMoisture = "মাটির আর্দ্রতা সম্পৃক্তি (% sat)",
        lithology = "ভূতাত্ত্বিক শিলা গ্রুপ (Lithology)",
        landCover = "ভূমি আচ্ছাদন (Land Cover)",
        runAssessment = "ভূ-কারিগরি ঝুঁকি মূল্যায়ন চালান",
        runningInference = "পূর্বাভাস চলছে...",
        failureProbability = "ঢাল ধসের আনুমানিক সম্ভাবনা",
        contributingFactors = "গুরুত্বপূর্ণ কারণসমূহ",
        tabAlerts = "সতর্কতা",
        tabMap = "মানচিত্র",
        tabReport = "প্রতিবেদন",
        tabProfile = "প্রোফাইল",
        languageDialogTitle = "ভাষা ও উপভাষা",
        languageDialogSub = "পূর্ব হিমালয় টেলিমেট্রি",
        filterByState = "রাজ্য / অঞ্চল অনুসারে ফিল্টার করুন"
    )

    val NE = AppStrings(
        langCode = "ne",
        telemetryRadarActive = "टेलिमेट्री रडार: सक्रिय",
        appTitle = "भूरक्षक",
        appSubtitle = "हिमालयी पहिरो पूर्व चेतावनी र उद्धार",
        rainfall = "वर्षा",
        soilSat = "माटोको ओसिलो",
        sectors = "सेक्टरहरू",
        live = "लाइभ",
        emergencySosTitle = "आपतकालीन SOS प्रेषण",
        emergencySosSubtitle = "SDRF / NDMA लाई एक-ट्याप GNSS प्रसारण",
        transmit = "पठाउनुहोस्",
        triggerSosPrompt = "आपतकालीन SOS पठाउने?",
        sosDescription = "यसले तपाईंको प्रमाणित GPS निर्देशांकहरू सिधै राज्य विपद् व्यवस्थापन र उद्धार टोलीहरूमा पठाउँछ।",
        cancel = "रद्द गर्नुहोस्",
        aiHazardNeuralCore = "एआई पहिरो न्यूरल कोर",
        online = "अनलाइन",
        aiHazardDescription = "२४ घण्टाको वर्षा र भू-उचाइ मोडेल प्रयोग गरी भिरालो जमिन खस्ने जोखिमको मूल्यांकन गर्नुहोस्।",
        calculateRisk = "जोखिम नाप्नुहोस्",
        doppler = "डपलर",
        regionalHazardFeed = "क्षेत्रीय विपद् सूचना",
        activeAlertsSuffix = "पूर्वी हिमालयमा सक्रिय चेतावनीहरू",
        liveFeedBadge = "लाइभ फिड",
        filterAll = "सबै",
        filterCritical = "गम्भीर",
        filterWarning = "चेतावनी",
        filterAdvisory = "सल्लाह",
        predictionScreenTitle = "एआई जोखिम मूल्यांकन",
        predictionScreenSub = "भूरक्षक XGBoost मोडेल",
        geotechnicalScenarios = "भू-प्राविधिक परिदृश्य",
        scenarioSub = "द्रुत सिमुलेशन छान्नुहोस् वा तल तथ्यांक भर्नुहोस्",
        scenarioCloudburst = "मनसुनी बादल फुट्ने",
        scenarioModerate = "मध्यम पहाडी वर्षा",
        scenarioDry = "सुक्खा पहाडी भिरालो",
        slopeTelemetryHeader = "भिरालो र मौसम विज्ञान टेलिमेट्री",
        elevation = "उचाइ (समुद्र सतहबाट m MSL)",
        slopeAngle = "भिरालोपन कोण (डिग्री °)",
        rainfall1d = "२४ घण्टाको वर्षा (mm)",
        rainfall3d = "३ दिनको संचित वर्षा (mm)",
        rainfall7d = "७ दिनको कुल वर्षा (mm)",
        soilMoisture = "माटोको ओसिलोपन (% sat)",
        lithology = "भूवैज्ञानिक चट्टान समूह (Lithology)",
        landCover = "भूमि आवरण वर्ग (Land Cover)",
        runAssessment = "भू-प्राविधिक जोखिम मूल्यांकन गर्नुहोस्",
        runningInference = "गणना भइरहेको छ...",
        failureProbability = "पहिरो जाने सम्भाव्यता",
        contributingFactors = "मुख्य कारकहरू",
        tabAlerts = "चेतावनी",
        tabMap = "नक्सा",
        tabReport = "रिपोर्ट",
        tabProfile = "प्रोफाइल",
        languageDialogTitle = "भाषा र स्थानीय बोली",
        languageDialogSub = "पूर्वी हिमालय क्षेत्र",
        filterByState = "राज्य / क्षेत्र अनुसार खोज्नुहोस्"
    )

    fun get(code: String): AppStrings {
        return when (code.lowercase()) {
            "hi" -> HI
            "as" -> AS
            "bn" -> BN
            "ne" -> NE
            else -> EN
        }
    }
}

val LocalAppStrings = staticCompositionLocalOf<AppStrings> {
    AppStringsRepository.EN
}
